### ISSUE TITLE
Disable option “ Update Engineering status of Project elements” from tpisg0163m000

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#224]
From: Esg Pragasam [mailto:esgpragasam@isgec.co.in] 
Sent: 11 December 2019 09:35
To: veena.pawar@isgec.co.in
Cc: 'Hariharan'; 'Baan Support'; k. viswananthan
Subject: FW: Element closing 

Madam

Refer our discussions, Kindly disable the “ Update Engineering status of Project elements” which is available in the specific menu for time being. We will once again check this utility in test server and doubly ensure its logic prior to placing it again. 

Accidental closing causing many execution issues for projects and kindly do the needed. 

CC-Rajesh – Please get the case no from Veena madam and check the functionality in test server and report me the fining to decide revoking the above decision.

Thanks
ESG Pragasam
Ph+919818995687
Extn-1669

**Comment by adarsh-isgec** [comment]
Form Command Disabled

**Comment by veena-isgec** [comment]
required on test server only temporarily for testing. done.
