### ISSUE TITLE
Subcontracting Item receipt should not be allowed more than PO Value

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#25]
Subcontracting Item receipt should not be allowed more than PO Value

**Comment by hariharan-isgec** [comment]
@veena-isgec As discussed with BKM the standard functionality of exceeding the PO value is acceptable, The PO Summary and Purchase Bill Approval Memo should reflect the original PO value to ensure manual control.

**Comment by hariharan-isgec** [comment]
#24 Is also related this issue

**Comment by veena-isgec** [comment]
Now being handled through #90
