### ISSUE TITLE
CR-374-Issue while linking document in post order due to different element of PO and document

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#256]
DCR-374   is raised on Joomla Portal for Remove the Element Check for Isgec Drawing   Linking function at Session (dmisg1134m500), as below stated. Please do the   needful as soon as possible. In Session "Send Vendor Document for   Technical Clearance post Order (dmisg1134m500)", please remove the check   of Element (in which PO created) at Link Document function at Specific menu.   Case :- As per screen shot, we found many cases where user could not able to   link the Isgec Drawing Number with reviewed Vendor Drawing in IDMS process.   Because Project Manager/Engineer create the PO of Engineering   Drawing/Document in other Budget Element bases on sanction availability. User   unable to assign UID from PMDL since Element of PO and PMDL does not match.   Engineer place the document in correct Element & shall be allowed to link   correct element by removing this check.
--

**Comment by veena-isgec** [comment]
copied to live

**Comment by ravik200** [comment]
[Test Document for Change in check on post order document linking.docx](https://github.com/Isgec/ERPLN/files/5161261/Test.Document.for.Change.in.check.on.post.order.document.linking.docx)
Test Document

**Comment by veena-isgec** [comment]
receved UST mail from Rajesh on 11 November 2020 16:33

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close
