### ISSUE TITLE
IR136997-Error msg not displayed when own reg no. in PO line and extension not match

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#261]
P3010712-Error msg not displayed when own reg no. in PO line and extension not match. This is happening in case when PO status is InProcess. For POs in Approved status Error msg is working fine.

**Comment by veena-isgec** [comment]
copied to live.

**Comment by ravik200** [comment]
Rollback script due to its creating new PO revision by while executing Purchase Order.
