### ISSUE TITLE
CR-565-Modifications in BOM Extraction Program(for ERP LN) to incorporate refrence Drawing Part Items

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#269]
2 New Tables would be created same as dmisg002 and dmisg004

Named as "Child Items of Reference Drawings" and "Part Items of Reference Drawings" respectivily.

**Comment by ravik200** [comment]
2 new tables are created dmisg021 - Child Items of Reference Drawings and dmisg022 - Part Items of Reference Drawings

In both test and live server.

**Comment by veena-isgec** [comment]
done.
