### ISSUE TITLE
CR578-In Financial Transaction voucher  "Annexure of Cashflow" not required

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#280]
In Financial Transaction voucher - tfisg1402m000, "Annexure of Cashflow" not required. In place of ISGEC GSTIN and BP GSTIN, Request amount and Mode of payment required.

**Comment by Techvikas-fbd** [comment]
Duplicate as CR-578-Modification in Financial Transaction voucher print #279

**Comment by veena-isgec** [comment]
closed through GH #279
