### ISSUE TITLE
CR-591 Modifications in Sale Invoice for company 651

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#289]
While printing of sales Invoice from session "ciisg2405m100" in co. 651, Annexure to the Invoice is not printed. Name of Company on Letter is not Correct. Alignment of Company name and address are not proper on the Tax Invoice.

**Comment by ravik200** [comment]
table ciisg011 maintain in company 651 and report script changes for ciisg24050103.

**Comment by veena-isgec** [comment]
copied to live
