### ISSUE TITLE
CR599-Modification in format of Reports requested by Guha

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#295]
Session Name	Code
1.	Print IR Wise Receipt Status	tfisg2400m018
2.	Print Detail of Export Sales	tdisg8431m000
3.	Print Child Items to be indented	tcisg0404m10

**Comment by ravik200** [comment]
New reports are created for above sessions

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to Production, please close.
