### ISSUE TITLE
CR-612 Session “IR (Received Purchase Invoices – tfacp1500m000)” required to be attached

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#312]
Session “IR (Received Purchase Invoices – tfacp1500m000)”   required to be attached in “Purchase Order Invoice Booking session –   tfisg1201m000” (PTR Booking session) and Payment request – tfsml0520m000   & tfmsl0120m000”.
--

**Comment by ravik200** [comment]
Session are added in specific in test and live server both

**Comment by ravik200** [comment]
Display Sessions are created

**Comment by veena-isgec** [comment]
moved to production

**Comment by veena-isgec** [comment]
From: Pawan Sharma [mailto:pawan.sharma1@isgec.co.in] 
Sent: 21 May 2020 11:50
To: Veena
Cc: 'subhranshu saha'; bhupinder.malik@isgec.co.in
Subject: Remove IR session from payment request

Dear Madam

Please remove Session “IR” from session “Payment request – tfsml0520m000 & tfmsl0120m000”.

Regards
Pawan Sharma

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to Production, please close.
