### ISSUE TITLE
CR614-open Purchase Bill Approval Memo from session “Billing Advice (Accounts)

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#314]
Session “Purchase Bill Approval Memo (WH) – whisg3410m000”   specific menu of session “Billing Advice (Accounts) – tdisg8131m600”.
--

**Comment by ravik200** [comment]
Session are added in specific in test and live server both

**Comment by veena-isgec** [comment]
Done on Production  and test both, no script change required.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to Production, please close.
