### ISSUE TITLE
IR142243-wrong batch no. display in session Purchase Order Invoice Processing

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#325]
wrong batch no. display in session Purchase Order Invoice Processing

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test this github.

**Comment by ravik200** [comment]
@veena-isgec mam, already in live and github updated

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
