### ISSUE TITLE
IR-42958 Fatal Error in quick PTR on selection of IR without Receipt

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#344]
TO handle Fatal Error in quick PTR on selection of IR without Receipt, user should get proper Error message

**Comment by veena-isgec** [comment]
Incident 14568768

**Comment by veena-isgec** [comment]
Above incident is not related to this github issue

**Comment by veena-isgec** [comment]
@ravik200 please update status of this github

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
