### ISSUE TITLE
IR142819-If blocked item is present in drawing with zero quantity then system should not stop Drawing approval

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#346]
If blocked item is present in drawing with zero quantity then system should not stop Drawing approval

**Comment by veena-isgec** [comment]
@Pankaj9583 please test on 37 server.

**Comment by ravik200** [comment]
@veena-isgec mam, Moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
