### ISSUE TITLE
CR641-Billing Advice Status Report

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#349]
Billing Advice Status Report

**Comment by veena-isgec** [comment]
@Pankaj9583 Please upload share tested checklist in github.

**Comment by Pankaj9583** [comment]
[CR641-GH349-Billing Advice Status Report-Testing Checklist.xlsx](https://github.com/Isgec/ERPLN/files/4823215/CR641-GH349-Billing.Advice.Status.Report-Testing.Checklist.xlsx)

**Comment by veena-isgec** [comment]
UAT mail received from Pawan Sharma on 03 July 2020 16:15

**Comment by veena-isgec** [comment]
@ravik200 solution installed on live. Please check once and update script.

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live, please close.
