### ISSUE TITLE
CR541-Handling of AS BUILT Drawing Release 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#350]
1.	While assigning document to draftman in ERP, system will check its DCR Category , if it is “As Built” then System will update the “As Built” flag(new field) in Document master as YES  and will pop up a message to user for it.
2.	While approval of document system will check “As Built” flag from document master , if it is YES then Element status will not be checked for its release. A confirmation will be taken from approver for approval of “AS Built” Document.
3.	“As built” flag will be visible in Document Assignment, Review and approval sessions and in Document Master.

**Comment by veena-isgec** [comment]
Testing checklist document 
[CR541-GH350-Testing Checklist-Handling of AS BUILT Drawing Release.xlsx](https://github.com/Isgec/ERPLN/files/4837189/CR541-GH350-Testing.Checklist-Handling.of.AS.BUILT.Drawing.Release.xlsx)

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test and update checklist with feedback.

**Comment by Pankaj9583** [comment]
[CR541-GH350-Testing.Checklist-Handling.of.AS.BUILT.Drawing.Release.xlsx](https://github.com/Isgec/ERPLN/files/4840094/CR541-GH350-Testing.Checklist-Handling.of.AS.BUILT.Drawing.Release.xlsx)
Testing done and working fine

**Comment by Pankaj9583** [comment]
[CR541-GH350-Testing.Checklist-Handling.of.AS.BUILT.Drawing.Release.xlsx](https://github.com/Isgec/ERPLN/files/4840095/CR541-GH350-Testing.Checklist-Handling.of.AS.BUILT.Drawing.Release.xlsx)
Testing done and working fine

**Comment by veena-isgec** [comment]
UAT mail received from Rajesh on 15 July 2020 18:01

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live , please close.
