### ISSUE TITLE
CR659-For new Projects Revised Initial Budget should be same as Total Budget

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#351]
For new Projects Revised Initial Budget should be same as Total Budget

**Comment by ravik200** [comment]
[Test Document for new Projects Revised Initial Budget should be same as Total Budget.docx](https://github.com/Isgec/ERPLN/files/5245233/Test.Document.for.new.Projects.Revised.Initial.Budget.should.be.same.as.Total.Budget.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Sandeep on 24 September 2020 14:51

**Comment by veena-isgec** [comment]
@ravi, please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
