### ISSUE TITLE
CR658-SAR Improvement points

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#353]
SAR Improvement points - 

1.	Maintain SAR Information session(Tpisg0174m000) - 
a.	Related Drawing Number entry field character length to be increase up to 125 character.
b.	Responsible Person's label to be added with text (Design) 
c.	Problem Identified/Raised at site Date Label text (Based on Excel Date) to be removed in Session
d.	SAR Severity – default option will be “Select SAR Severity”
e.	Vipul will revert for change in label of Responsible department
f.	Zoom of Responsible Person will be from session dmisg1152m000
2.	Display SAR Session (tpisg0574m100) - 
a.	Change Label “Login” to “SAR Login”
b.	Display Login Name
c.	Rename label “Created by” as  “Prepared by” and show Prepared By text field here.
d.	Add field Discipline next to Responsible person
3.	SAR reviewer reassign session (tpisg0274m000)
a.	Change zoom of reviewer to dmisg1152m000
b.	Old Reviewer Name to be displayed

4.	SAR Approver reassign session (tpisg0274m001)
a.	Change zoom of approver to tpisg0173m000
b.	Old Approver Name to be displayed

5.	All codes to be displayed with description in sessions tpisg0174m000 , tpisg0574m000
.

**Comment by ravik200** [comment]
[Test Document for SAR Improvement points.docx]

**Comment by Pankaj9583** [comment]
[CR658-SAR Improvement points.xlsx](https://github.com/Isgec/ERPLN/files/4849441/CR658-SAR.Improvement.points.xlsx)
testing done  and working fine in test server-37

**Comment by veena-isgec** [comment]
Testing checklist with feedback.
[CR658-505-GH353-Testing checklist-SAR Improvement points.xlsx](https://github.com/Isgec/ERPLN/files/4849527/CR658-505-GH353-Testing.checklist-SAR.Improvement.points.xlsx)

**Comment by veena-isgec** [comment]
UAT mail received from Vipul dated 15 July 2020 18:01

**Comment by veena-isgec** [comment]
@ravik200 Plese move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live,, please close.
