### ISSUE TITLE
CR646-Display option in Remittance letter from Quick Payment functionality

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#355]
Display option also required along with printing in Option "Print Remittance letters for cheque Printing" in session "Quick Payment process-tfisg1189m100". Please provide selection of Print or display along with the option on the face of the session-tfisg1189m100

**Comment by veena-isgec** [comment]
Received UAT from Pawan on 06-08-2020 17:27

**Comment by veena-isgec** [comment]
@ravi Please move to live

**Comment by ravik200** [comment]
Revert code due to performance

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close
