### ISSUE TITLE
CR681-Allow receipt confirmation in Back date

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#357]
Please allow receipt confirmation in Back date.
--

**Comment by veena-isgec** [comment]
From: Pawan Sharma [mailto:pawan.sharma1@isgec.co.in] 
Sent: 01 July 2020 16:38
To: 'BaaN Support'
Cc: bhupinder.malik@isgec.co.in; Veena; piyush.dixit@isgec.co.in; amar.saxena@isgec.co.in
Subject: FW: WHR of Bholaram Invoices

Dear Team

Please restrict back date confirmation of Receipt.

Regards
Pawan Sharma

**Comment by veena-isgec** [comment]
Please Restrict again

**Comment by veena-isgec** [comment]
@ravik200 Please restrict again

**Comment by ravik200** [comment]
@veena-isgec Restricted again

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live please close.
