### ISSUE TITLE
CR657-Blocking Items in Drawing having unit LOT

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#360]
Blocking of Items in Drawing having unit LOT

**Comment by veena-isgec** [comment]
[CR657-GH360-Testing Checklist-Blocking Items in Drawing having unit LOT.xlsx](https://github.com/Isgec/ERPLN/files/4901064/CR657-GH360-Testing.Checklist-Blocking.Items.in.Drawing.having.unit.LOT.xlsx)

**Comment by Pankaj9583** [comment]
[CR657-GH360-Testing.Checklist-Blocking.Items.in.Drawing.having.unit.LOT.xlsx](https://github.com/Isgec/ERPLN/files/4906474/CR657-GH360-Testing.Checklist-Blocking.Items.in.Drawing.having.unit.LOT.xlsx)
Testing done and working fine

**Comment by veena-isgec** [comment]
UAT mail received from Rajesh 15 July 2020 22:05

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live,, please close.
