### ISSUE TITLE
CR665-Customer Code and description in Billing Report

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#366]
Customer Code and description in Billing Report

**Comment by veena-isgec** [comment]
[CR665-GH366-Testing Checklist-Customer Code and description in Billing Report.xlsx](https://github.com/Isgec/ERPLN/files/4911864/CR665-GH366-Testing.Checklist-Customer.Code.and.description.in.Billing.Report.xlsx)

@Pankaj, plest test and upload updated checklist.

**Comment by Pankaj9583** [comment]
[CR665-GH366-Testing.Checklist-Customer.Code.and.description.in.Billing.Report.xlsx](https://github.com/Isgec/ERPLN/files/4912289/CR665-GH366-Testing.Checklist-Customer.Code.and.description.in.Billing.Report.xlsx)
testing done & working fine

**Comment by veena-isgec** [comment]
UAT received from Pawan on 23 July 2020 16:51

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hari moved to live please close.
