### ISSUE TITLE
CR673-Modifications in Manhours booking module for 9 hrs 30 min

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#367]
Modifications in Manhours booking module for 9 hrs 30 min

**Comment by ravik200** [comment]
[Test Document for Modifications in Man hours booking module for 9 hrs 30 min.docx](https://github.com/Isgec/ERPLN/files/4916489/Test.Document.for.Modifications.in.Man.hours.booking.module.for.9.hrs.30.min.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT Mail received from Rajesh Vashist on 18 July 2020 20:03

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
