### ISSUE TITLE
CR666-Payable, retention report from Payment Request

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#368]
Payable, retention report from Payment Request

**Comment by ravik200** [comment]
[Test Document for Payable.docx](https://github.com/Isgec/ERPLN/files/4918601/Test.Document.for.Payable.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Pawan on 23 July 2020 14:37

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by veena-isgec** [comment]
@hariharan-isgec  moved to live please close.
