### ISSUE TITLE
CR670-Add notes in Billing Advice

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#369]
notes in Billing Advice

**Comment by ravik200** [comment]
[Test Document for Add notes in Billing Advice.docx](https://github.com/Isgec/ERPLN/files/4937513/Test.Document.for.Add.notes.in.Billing.Advice.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 Please move to live as notes is not developed for 37 server.

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live. please close.
