### ISSUE TITLE
CR678-freeze Quick Payment session after matching PTR 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#370]
Data should be freezed in "Purchase order Invoicing Processing - tfisg1201m000" after matching.

**Comment by ravik200** [comment]
[Test Document for Freeze quick payment session after Matching.docx](https://github.com/Isgec/ERPLN/files/4937539/Test.Document.for.Freeze.quick.payment.session.after.Matching.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT Mail received from Pawan on  08-08-2020 13:18

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by ravik200** [comment]
Revert code due to performance

**Comment by veena-isgec** [comment]
@ravik200 please move to live again

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
