### ISSUE TITLE
CR679-Show Attachment flag in IR session

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#371]
On the face of the IR session it is not displayed that IR contains attachment or not.

**Comment by ravik200** [comment]
[Test Document for Display Attachment flag in IR Session.docx](https://github.com/Isgec/ERPLN/files/4941378/Test.Document.for.Display.Attachment.flag.in.IR.Session.docx)
Test Document

**Comment by veena-isgec** [comment]
Technically not possible in standard session tfacp1500m000,
Same was done in Customised session tfisg1500m100 which is working fine and moved to live.

Since user asked for standard session hence did not gave UAT.

**Comment by veena-isgec** [comment]
@hariharan-isgec move to live please close.
