### ISSUE TITLE
IR147016-Remove check from Reviewer session of PLM

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#372]
147016 Internal case log id
From: Rajesh kumar Vashist [mailto:rajesh.vashist@isgec.co.in] 
Sent: 18 July 2020 14:44
To: 'Veena'; veena.pawar@isgec.co.in; 'Baan Support'
Cc: 'NR Gopinathan'; 'Esg Pragasam'; 'Hariharan'; 'Naresh Kumar'; darshan.anand@isgec.co.in
Subject: RE: Screen shot problem faced in baan - regarding

Dear Mam,

As per your trailing mail reply, we need to PLM workflow access is required for all the user within the same discipline for across Divisions Projects. Please do the needful as soon as possible.

Thank & Regards,

Rajesh Kumar Vashist 
CESC

 
A-56, Sector 63, Noida – 201 301 U.P., India
Mobile : +91 84485 95663
Tel.: +91-120-458 1608
Website: www.isgec.com
**********************************************************************
Please save paper,to save our planet to live, use both side if u can.
**********************************************************************

From: Veena [mailto:veena@isgec.co.in] 
Sent: 18 July 2020 12:59
To: 'Rajesh kumar Vashist'; veena.pawar@isgec.co.in; 'Baan Support'
Cc: 'NR Gopinathan'; 'Esg Pragasam'; 'Hariharan'; 'Naresh Kumar'; darshan.anand@isgec.co.in
Subject: RE: Screen shot problem faced in baan - regarding

Dear Rajesh,

The root cause analysis says -

This issue comes when Reviewer and approver of a document belong to different divisions, Eg. Drawing belong to FGD, reviewer is from Boiler and approver is from FGD (this check was applied in system since implementation of ERP in 2014 and was not removed in CR331). 
Process works fine when Drawing is of one division and  Reviewer and Approver are from another division provided both of them belong to same division. 
There is no change in logic since CR331 moved to live server in Oct 2019. 

The fix for this issue would be to remove the check where system force the  Reviewer and approver to be of same division.
Please confirm to remove this check.

Regards
Veena

From: Rajesh kumar Vashist [mailto:rajesh.vashist@isgec.co.in] 
Sent: 17 July 2020 20:17
To: veena.pawar@isgec.co.in; 'Baan Support'
Cc: 'NR Gopinathan'; 'Esg Pragasam'; 'Hariharan'; 'Naresh Kumar'; darshan.anand@isgec.co.in
Subject: RE: Screen shot problem faced in baan - regarding

Dear Madam,

Same condition data is available with same user with Status “Under Review”. Please do the needful as soon as possible..

FS0003-67170200-MWS-0001 to FS0003-67170200-MWS-0010.

Thank & Regards,

Rajesh Kumar Vashist 
CESC

 
A-56, Sector 63, Noida – 201 301 U.P., India
Mobile : +91 84485 95663
Tel.: +91-120-458 1608
Website: www.isgec.com
**********************************************************************
Please save paper,to save our planet to live, use both side if u can.
**********************************************************************

From: Veena [mailto:veena@isgec.co.in] 
Sent: 17 July 2020 18:55
To: 'Rajesh kumar Vashist'; veena.pawar@isgec.co.in
Cc: 'NR Gopinathan'; 'Esg Pragasam'; 'Hariharan'; 'Baan Support'; 'Naresh Kumar'; darshan.anand@isgec.co.in
Subject: RE: Screen shot problem faced in baan - regarding

Dear Rajesh,

As discuss just now, the transaction mentioned in below mail is resolved by baansupport as a transactional case, Please provide one more case of this problem to find the root cause.

Regards
Veena

From: Rajesh kumar Vashist [mailto:rajesh.vashist@isgec.co.in] 
Sent: 17 July 2020 16:46
To: veena.pawar@isgec.co.in
Cc: 'NR Gopinathan'; 'Esg Pragasam'; 'Hariharan'; 'Baan Support'; 'Naresh Kumar'; darshan.anand@isgec.co.in
Subject: RE: Screen shot problem faced in baan - regarding

Dear Madam,

Please check  on live server, customisation against DCR-331 is not working. Please do the needful as soon as possible.

Thank & Regards,

Rajesh Kumar Vashist 
CESC

 
A-56, Sector 63, Noida – 201 301 U.P., India
Mobile : +91 84485 95663
Tel.: +91-120-458 1608
Website: www.isgec.com
**********************************************************************
Please save paper,to save our planet to live, use both side if u can.
**********************************************************************

From: Rajesh kumar Vashist [mailto:rajesh.vashist@isgec.co.in] 
Sent: 16 July 2020 18:12
To: 'veena.pawar@isgec.co.in'
Cc: 'NR Gopinathan'; 'Esg Pragasam'; 'Hariharan'; 'Baan Support'; 'Naresh Kumar' (naresh.kumar1@isgec.co.in); 'darshan.anand@isgec.co.in'
Subject: RE: Screen shot problem faced in baan - regarding

Dear Madam,

As per DCR-331,dt: 29/1/2019, there is no restriction for PLM Workflow  activity with inter division users with same discipline. But as screen shot shown in trailing mail require functionality not working for Session “Document Review Functionality (dmdisg0101m300)”
Please do the needful.

Thank & Regards,

Rajesh Kumar Vashist 
CESC

 
A-56, Sector 63, Noida – 201 301 U.P., India
Mobile : +91 84485 95663
Tel.: +91-120-458 1608
Website: www.isgec.com
**********************************************************************
Please save paper,to save our planet to live, use both side if u can.
**********************************************************************

From: Baan Support [mailto:baansupport@isgec.co.in] 
Sent: 16 July 2020 17:19
To: 'Rajesh kumar Vashist'
Cc: 'NR Gopinathan'; veena.pawar@isgec.co.in; 'Esg Pragasam'; 'Hariharan'
Subject: RE: Screen shot problem faced in baan - regarding

Please ask user to check now

Regards 
Baan Support Team
IT & System
ISGEC HEAVY ENGINEERING LTD.
A-8, Sector 63, Second Floor
Noida -201301 (UP)
0120-4085500, Extn No:- 7219

 Every 3000 sheets of paper cost us a tree. Let's consider our environmental responsibility before printing this e-mail - Save paper

From: Rajesh kumar Vashist [mailto:rajesh.vashist@isgec.co.in] 
Sent: 16 July 2020 17:13
To: 'Baan Support'
Cc: 'NR Gopinathan'; veena.pawar@isgec.co.in; 'Esg Pragasam'; 'Hariharan'
Subject: FW: Screen shot problem faced in baan - regarding

Dear Pankaj,

Please check the trailing mail issue, User (2090 belong to Mech, Boiler) not able to process the drawing for Approval functionality  to required Approver(3419 belong to Mech, FGD) , because of Approver not shown in selection zoom window of Session “Document Review Functionality (dmisg0101m300)”. 

Please do the needful as soon as possible.

Thank & Regards,

Rajesh Kumar Vashist 
CESC

 
A-56, Sector 63, Noida – 201 301 U.P., India
Mobile : +91 84485 95663
Tel.: +91-120-458 1608
Website: www.isgec.com
**********************************************************************
Please save paper,to save our planet to live, use both side if u can.
**********************************************************************

From: NR Gopinathan [mailto:gopinathan_nr@isgec.co.in] 
Sent: 16 July 2020 16:31
To: Rajesh kumar Vashist
Cc: darshan.anand@isgec.co.in; 'Naresh Kumar'
Subject: FW: Screen shot problem faced in baan - regarding

Dear Sir,
         Pls. find the screen shot. My name is not coming in approver list. Requested to Pls. resolve the issue. Pls. note this work has been done by Industrial boiler team

Regards,
Gopinathan

From: Darshan [mailto:darshan.anand@isgec.co.in] 
Sent: 16 July 2020 16:27
To: 'n.r. gopinathan'
Subject: FW: Screen shot problem faced in baan - regarding

Sir,
fyi

From: Naresh Kumar [mailto:naresh.kumar1@isgec.co.in] 
Sent: 16 July 2020 16:13
To: 'Darshan'
Subject: Screen shot problem faced in baan - regarding

Sir,

Please see the problem discussed.

 

Thanks & Regards
 
Naresh Kumar
Boiler-Design
 
A-56 , Sector-63 , Noida-201301 (U.P), India
Tel.: +91-120-4581663
Mobile : +91-8448595757
Website: www.isgec.com
   
 please consider the environment before printing this e-mail

**Comment by ravik200** [comment]
[Test Document for IR147016.docx](https://github.com/Isgec/ERPLN/files/4941558/Test.Document.for.IR147016.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Rajesh on 23 July 2020 13:32

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live please close.
