### ISSUE TITLE
CR687-Modifications in Print Manhours data report

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#373]
Report session “Print Man-hours Data (tiisg9410m030)” not showing the entire data as per input fill in the session. We are taking the report for Project JB1070 man-hour consume. But report not data for the left users (1409 & 1588) , those were worked on this project. For your reference incomplete reports are attached. Please do the needful as soon as possible.

**Comment by ravik200** [comment]
[Test Document for Modifications in Print Man hours data report.docx](https://github.com/Isgec/ERPLN/files/4952405/Test.Document.for.Modifications.in.Print.Man.hours.data.report.docx)
Test Document

**Comment by Pankaj9583** [comment]
[CR687-Modifications in Print Manhours data report.xlsx.xlsx](https://github.com/Isgec/ERPLN/files/4953981/CR687-Modifications.in.Print.Manhours.data.report.xlsx.xlsx)
Testing done and working fine (Testing file attached)

**Comment by veena-isgec** [comment]
UAT mail received from Rajesh on 22 July 2020 11:02, hence moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live please close.
