### ISSUE TITLE
CR685-Open entries should open automatically from Payment request

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#374]
Please attach display of session "Invoice from business partner Open Entries - tfacp2520m000" in specific menu of session Payment request "tfmsl0120m000" & "tfmsl0520m000". By default open entries should open for the BP of selected line.

**Comment by ravik200** [comment]
[Test Document for Open entries should open automatically from Payment request.docx](https://github.com/Isgec/ERPLN/files/4953186/Test.Document.for.Open.entries.should.open.automatically.from.Payment.request.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Pawan on 21 July 2020 18:54

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hari moved to live, please close.
