### ISSUE TITLE
Receipted qty more than engg qty in Child item tracking history

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#375]
Receipted qty more than engg qty in Child item tracking history(tcisg0404m300), Correction required in Quantity field.

![image](https://user-images.githubusercontent.com/43699482/88055176-28da4d80-cb7c-11ea-9a86-8bea1dfaf27d.png)

**Comment by ravik200** [comment]
[Test Document for Receipted qty more than engg qty in Child item tracking history.docx](https://github.com/Isgec/ERPLN/files/6088090/Test.Document.for.Receipted.qty.more.than.engg.qty.in.Child.item.tracking.history.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
