### ISSUE TITLE
SAR MIS Report not shows full problem description

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#378]
SAR MIS Report not shows full problem description

**Comment by ravik200** [comment]
[Test Document for SAR MIS Report not shows full problem description.docx](https://github.com/Isgec/ERPLN/files/5010408/Test.Document.for.SAR.MIS.Report.not.shows.full.problem.description.docx)
Test Document

**Comment by veena-isgec** [comment]
Received UAT mail from Vipil on 20 August 2020 18:34

**Comment by veena-isgec** [comment]
@ravik200 pls move to live.

**Comment by veena-isgec** [comment]
@hari moved to live, please close.
