### ISSUE TITLE
CR686-Update PROJECT  PO in tfacp200

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#379]
CR686-Update PROJECT  PO in tfacp200 in old data

**Comment by ravik200** [comment]
[Test Document for CR686.docx](https://github.com/Isgec/ERPLN/files/5028338/Test.Document.for.CR686.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT received from Accounts on 08 August 2020 13:18

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live , please close.
