### ISSUE TITLE
CR374-Modification in element check in Post order document linking

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#380]
CR374-Modification in element check in Post order document linking

**Comment by ravik200** [comment]
[Test Document for Change in check on post order document linking.docx](https://github.com/Isgec/ERPLN/files/5229758/Test.Document.for.Change.in.check.on.post.order.document.linking.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close
