### ISSUE TITLE
IR149437-Functional Error in SAR re-assigning to Reviewer & Approver on SAR Sessions

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#381]
Functional Error in SAR re-assigning to Reviewer & Approver on SAR Sessions

**Comment by Pankaj9583** [comment]
[Functional Error in SAR re-assigning to Reviewer & Approver on SAR Sessions.xlsx](https://github.com/Isgec/ERPLN/files/5199070/Functional.Error.in.SAR.re-assigning.to.Reviewer.Approver.on.SAR.Sessions.xlsx)
Testing done and working fine.

**Comment by ravik200** [comment]
@veena-isgec, Moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
