### ISSUE TITLE
CR-700-Facility to attach documents in Business partner

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#382]
Facility to attach documents in Business partner-tccom4500m000

**Comment by ravik200** [comment]
[Test Document for Facility to attach documents in Business partners.docx](https://github.com/Isgec/ERPLN/files/5049486/Test.Document.for.Facility.to.attach.documents.in.Business.partners.docx)
Test Document

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live please close.
