### ISSUE TITLE
CR674-Functionality required for finalization of bank payment transactions Batch

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#384]

**Comment by veena-isgec** [comment]
Functionality required for finalization of bank payment transactions Batch

**Comment by veena-isgec** [comment]
UAT mail received from Pawan on August 7, 2020 10:11 AM

**Comment by veena-isgec** [comment]
@ravi, solution GH384CR681_000 moved to live, please update github

**Comment by veena-isgec** [comment]
@ravik200 solution GH384CR681_000 moved to live, please update github

**Comment by ravik200** [comment]
@veena-isgec mam, github updated.

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live, please close.
