### ISSUE TITLE
CR680-Report required for status of Purchase order

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#385]
CR680-Report required for status of Purchase order

**Comment by veena-isgec** [comment]
@ravik200 confirmation received from Hariharan Sir to move to live on 23 September 2020 18:00.
This report is thoroughly tested by IT on test server and would be further tested on live.

**Comment by veena-isgec** [comment]
@ravik200 session code is tfisg1485m000

**Comment by ravik200** [comment]
@veena-isgec mam, Moved to live, Please test session in live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
