### ISSUE TITLE
CR710-HR Circular for (regular working hours viz., 8:45 am to 5:30 pm will be restored at Noida offices.)

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#387]
As per trailing mail from HR Circular for (regular working hours viz., 8:45 am to 5:30 pm will be restored at Noida offices.), We need to restore the condition before DCR raised for “DCR-673 raised on Joomla for Work hours Updation in BaaN” Previous working time “ 8 & 1/4th Hours (8.25 decimal hours) logging.

**Comment by ravik200** [comment]
[Test Document for Modifications in Print Man hours data report.docx](https://github.com/Isgec/ERPLN/files/5094088/Test.Document.for.Modifications.in.Print.Man.hours.data.report.docx)
Test Document

**Comment by veena-isgec** [comment]
Received UAT mail from Rajesh on 19 August 2020 16:24

**Comment by veena-isgec** [comment]
@ravik200 pls move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close
