### ISSUE TITLE
CR709-PO Series check on Purchase Order creation/modification

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#388]
CR709-PO Series check on Purchase Order creation/modification

**Comment by ravik200** [comment]
[Test Document for PO Series check on Purchase Order creation.docx](https://github.com/Isgec/ERPLN/files/5134234/Test.Document.for.PO.Series.check.on.Purchase.Order.creation.docx)

Test Document

**Comment by Pankaj9583** [comment]
[CR709-PO Series check on Purchase Order creation and modification GH388.docx](https://github.com/Isgec/ERPLN/files/5145006/CR709-PO.Series.check.on.Purchase.Order.creation.and.modification.GH388.docx)
Testing done and its working fine (testing document attached).

**Comment by veena-isgec** [comment]
UAT Mail received from Mr. Ajay Gupta on 14 September 2020 14:48

**Comment by veena-isgec** [comment]
@ravi please move the master session to live first, For check i will let you know once master data is entered by Materials.

**Comment by ravik200** [comment]
@veena-isgec mam, Solution GH388CR709 is exported from server 44, please move to live.

**Comment by ravik200** [comment]
New Solution exported GH388CR709_000, please move to live

**Comment by veena-isgec** [comment]
@ravik200 master updated , please move the check on live.

**Comment by veena-isgec** [comment]
@ravik200 please exclude whinh3512m000, tdpur4106mooo from this check.

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
