### ISSUE TITLE
CR722-Sale Invoice in HTML Format

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#390]
Sale Invoice in HTML Format

**Comment by veena-isgec** [comment]
@ravik200 please attach testing document

**Comment by veena-isgec** [comment]
@Pankaj9583 PLease attach testing document

**Comment by Pankaj9583** [comment]
[CR722-Sale Invoice in HTML Format 390.pdf](https://github.com/Isgec/ERPLN/files/5153980/CR722-Sale.Invoice.in.HTML.Format.390.pdf)
Testing done and its working fine (3 Invoice Print out from HTML format and Normal Session attached)

**Comment by ravik200** [comment]
[Test Document for Sale Invoice in HTML Format.docx](https://github.com/Isgec/ERPLN/files/5160251/Test.Document.for.Sale.Invoice.in.HTML.Format.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail Received from Mr. Rakesh Sharma on 10 September 2020 17:52

**Comment by veena-isgec** [comment]
@ravik200 Please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, Solution GH390CR722_000 move to live from server 37

**Comment by ravik200** [comment]
@veena-isgec mam, New Solution GH390CR722_001 Sale Invoice in HTML Format - table ciisg801 is exported, Please move to live from server 37.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live. please close.
