### ISSUE TITLE
CR714-Vehicle No. mandatorily required in export invoice in respect of full load vehicles

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#391]
Make the Vehicle No.mandatory to enter in GR in respect of full load vehicles

Got concurrence from Mr. Ajay Gupta on 28 August 2020 15:24

**Comment by ravik200** [comment]
[Test Document for Vehicle No mandatory in GR.docx](https://github.com/Isgec/ERPLN/files/5160351/Test.Document.for.Vehicle.No.mandatory.in.GR.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test the changes

**Comment by Pankaj9583** [comment]
[CR714-Vehicle No. mandatorily required in export invoice in respect of full load vehicles.docx](https://github.com/Isgec/ERPLN/files/5166067/CR714-Vehicle.No.mandatorily.required.in.export.invoice.in.respect.of.full.load.vehicles.docx)
Testing done and ite working fine (screen shot attached)

**Comment by veena-isgec** [comment]
UAT mail received from Ajay Gupta on 03 September 2020 12:14

**Comment by veena-isgec** [comment]
@ravik200 Please upload to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
