### ISSUE TITLE
IR153343-Wrong EU in Vendor Pre Order and post order receipt in company 700

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#393]
Wrong EU in Vendor Pre Order and post order receipt in company 700

**Comment by ravik200** [comment]
[Test Document for Wrong EU in Vendor Pre Order and post order receipt in company 700.docx](https://github.com/Isgec/ERPLN/files/5166339/Test.Document.for.Wrong.EU.in.Vendor.Pre.Order.and.post.order.receipt.in.company.700.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.

**Comment by Pankaj9583** [comment]
[IR153343-Wrong EU in Vendor Pre Order and post order receipt in company 700.docx](https://github.com/Isgec/ERPLN/files/5173228/IR153343-Wrong.EU.in.Vendor.Pre.Order.and.post.order.receipt.in.company.700.docx)
Testing done and its working fine in both Post and pre order receipt

**Comment by veena-isgec** [comment]
@ravi bug tested ok on test server, please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.

**Comment by ravi** [comment]
Please stop tagging me. :-)
