### ISSUE TITLE
CR716-Pending Indent Report should consider the Indent not pending only when Indent is approved

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#395]
Pending Indent Report should consider the Indent not pending only when Indent is approved

**Comment by ravik200** [comment]
[Test Document for Pending Indent Report should consider the Indent not pending only when Indent is approved.docx](https://github.com/Isgec/ERPLN/files/5187276/Test.Document.for.Pending.Indent.Report.should.consider.the.Indent.not.pending.only.when.Indent.is.approved.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravi Sent for approval date not appearing when Pending checkbox is ticked. Please correct.

**Comment by veena-isgec** [comment]
UAT mail received from user on 11 September 2020 11:33

**Comment by veena-isgec** [comment]
@ravi Please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
