### ISSUE TITLE
IR154125-PAP not displayed in Quick PTR when advance adjusted

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#396]
PAP not displayed in Quick PTR when advance adjusted

**Comment by ravik200** [comment]
[Test Document for IR154125-PAP not displayed in Quick PTR when advance adjusted.docx](https://github.com/Isgec/ERPLN/files/5201008/Test.Document.for.IR154125-PAP.not.displayed.in.Quick.PTR.when.advance.adjusted.docx)
Live Test Document

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
