### ISSUE TITLE
PTR not cleared from IRN after deletion

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#398]
PTR not cleared from IRN after deletion

**Comment by ravik200** [comment]
[Test Document for PTR not cleared from IRN after deletion.docx](https://github.com/Isgec/ERPLN/files/5253611/Test.Document.for.PTR.not.cleared.from.IRN.after.deletion.docx)
Test Document

**Comment by veena-isgec** [comment]
@pankaj, Please test on test server.

**Comment by Pankaj9583** [comment]
[Test PTR Deletion - Copy.docx](https://github.com/Isgec/ERPLN/files/5267002/Test.PTR.Deletion.-.Copy.docx)
Testing done and working fine in test server.

**Comment by veena-isgec** [comment]
@ravik200 bug is thoroughly tested, please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec Tested ok on test and live server. please close
