### ISSUE TITLE
CR723- TDS related modification in BP Creation Request

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#401]
TDS shall be made a by default value in Tax Classification field on the Business Partner Role page of BP creation request session tcmslm1111000.
This change shall be applicable in all companies (200, 700 & 651)

**Comment by ravik200** [comment]
[Test Document for TDS related modification in BP Creation Request.docx](https://github.com/Isgec/ERPLN/files/5255215/Test.Document.for.TDS.related.modification.in.BP.Creation.Request.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.

**Comment by Pankaj9583** [comment]
[CR723- TDS related modification in BP Creation Request (#401).docx](https://github.com/Isgec/ERPLN/files/5321198/CR723-.TDS.related.modification.in.BP.Creation.Request.401.docx)
Testing done in teset server and TDS classification (TDS194C) available now

**Comment by veena-isgec** [comment]
UAT mail received from Vipul on 03 October 2020 11:53

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
