### ISSUE TITLE
CR730-Modifications in Supplier Payable/Retention Report

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#403]
Modifications in Supplier Payable/Retention Report

**Comment by ravik200** [comment]
[Test Document for Modification in Payable Retention report.docx](https://github.com/Isgec/ERPLN/files/5267836/Test.Document.for.Modification.in.Payable.Retention.report.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 
Following Gaps found -
1. Grand Total showing ####### when value is large, Please check for company 200,  Retention code 002, rest of the filters would be in full range.
2. Due Date seems wrong in few cases, please  check for POS P10124737, P10108157, 106145.

**Comment by veena-isgec** [comment]
UAT mail received from Saha ji on 25 September 2020 22:00

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
