### ISSUE TITLE
CR696-Customer code and Date filter to be added in Billing report-Projects

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#404]
Customer code and Date option required in Input form of report "Print Billing report-Projects-tpisg6400m200".

**Comment by ravik200** [comment]
[Test Document for Customer code and Date filter to be added in Billing report.docx](https://github.com/Isgec/ERPLN/files/5338509/Test.Document.for.Customer.code.and.Date.filter.to.be.added.in.Billing.report.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.

**Comment by Pankaj9583** [comment]
[CR696-Customer code and Name required in output.xlsx](https://github.com/Isgec/ERPLN/files/5352410/CR696-Customer.code.and.Name.required.in.output.xlsx)
Testing done and working fine (Testing Document attached)

**Comment by veena-isgec** [comment]
@ravik200 demonstrated the output to Mr. Rakesh Sharma through mail on 12 October 2020 10:12 and got his verbal confirmation. Please move to live.

**Comment by veena-isgec** [comment]
@Pankaj9583 please check on live.

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
