### ISSUE TITLE
IR155212-Add “Kgs” in “Total Weight” in Indent Report Printout

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#405]
-Add “Kgs” in “Total Weight” in Indent Report Printout

**Comment by ravik200** [comment]
Label Changed from "Total Weight" to "Total Weight(Kgs)" in tdisg2400m000(Indent Report) in all servers.

**Comment by veena-isgec** [comment]
@hariharan-isgec Tested ok on test and live servers, please close.
