### ISSUE TITLE
IR153899-IDMS not shows name of left users 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#406]
Case ID 153899- we observed that when user left from company then system not shown his name on his vetted document at IDMS module is session dmsig134m300 & dmisg134m500

**Comment by ravik200** [comment]
[Test Document for IDMS not shows name of left users.docx](https://github.com/Isgec/ERPLN/files/5275275/Test.Document.for.IDMS.not.shows.name.of.left.users.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, @Pankaj9583 sir, moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
