### ISSUE TITLE
IR153719-Issue of Group code filter in Report Print Manhour Data

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#407]
153719-Report Session “Print Manhour Data (tiisg9410m030)” is producing the additional data. Report not coming as per Group Code Filter is used in report input sheet.

**Comment by ravik200** [comment]
[Test Document for Issue of Group code filter in Report Print Manhour Data.docx](https://github.com/Isgec/ERPLN/files/5274621/Test.Document.for.Issue.of.Group.code.filter.in.Report.Print.Manhour.Data.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Rajesh Vashist on 5th Oct

**Comment by veena-isgec** [comment]
@ravik200  Please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
