### ISSUE TITLE
CR737- Upgrade Quick Payment session

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#409]
Modifications in Quick Payment session –
1.	Button “Display Payment Request “ on Header for selected Payment Request No.
2.	Button “Open Entries” on Header for Supplier of Selected Payment Request
3.	Button “Bank Voucher Print”  on  Header to open voucher No. of Payment Advice 
4.	Link “Print Purchase Order" on Line
5.	Link “Po Summary on Line”

**Comment by ravik200** [comment]
[Test Document for Upgrade Quick Payment Process.docx](https://github.com/Isgec/ERPLN/files/5382937/Test.Document.for.Upgrade.Quick.Payment.Process.docx)
Test Document

**Comment by Pankaj9583** [comment]
[CR737- Upgrade Quick Payment session 409.xlsx](https://github.com/Isgec/ERPLN/files/5395013/CR737-.Upgrade.Quick.Payment.session.409.xlsx)
Testing done and working fine (Testing document attached)

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
