### ISSUE TITLE
CR-738 Flag in session "Business partner-tccom4500m000" for attachment

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#410]
Flag in session "Business partner-tccom4500m000" for attachment

**Comment by veena-isgec** [comment]
@ravik200 add a new flag "Attachment Micro"

**Comment by ravik200** [comment]
[Test Document for Flag in session.docx](https://github.com/Isgec/ERPLN/files/5310021/Test.Document.for.Flag.in.session.docx)
Test Document

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
