### ISSUE TITLE
CR741-TCS on Sale Invoice

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#412]
TCS on Sale Invoice

**Comment by veena-isgec** [comment]
[Uploading CR741-GH412-Testing Check List - TCS on Sale Invoice.xlsx…]()

**Comment by veena-isgec** [comment]
@Pankaj9583 please check the changes as per testing checklist.

**Comment by Pankaj9583** [comment]
[TCS Testing.docx](https://github.com/Isgec/ERPLN/files/5321112/TCS.Testing.docx)
testing done and working fine

**Comment by veena-isgec** [comment]
UAT  received from user on 03 October 2020 10:34 on mail.

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
