### ISSUE TITLE
CR739-Display Billing Advice Status against FOC Receipts in PTR Print

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#413]
Display Billing Advice Status against FOC Receipts in PTR Print (CR739)

**Comment by ravik200** [comment]
[Test Document for Display Billing Advice Status against FOC Receipts in PTR Print.docx](https://github.com/Isgec/ERPLN/files/5346727/Test.Document.for.Display.Billing.Advice.Status.against.FOC.Receipts.in.PTR.Print.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.

**Comment by Pankaj9583** [comment]
[CR-739 Display Billing Advice Status against FOC Receipts in PTR Print.xlsx](https://github.com/Isgec/ERPLN/files/5352386/CR-739.Display.Billing.Advice.Status.against.FOC.Receipts.in.PTR.Print.xlsx)
Testing done and its working fine (Testing document attached)

**Comment by veena-isgec** [comment]
@ravik200 , Please move to live for further testing. Got agreement from Mr. Rakesh Sharma on 13 October 2020 10:08

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
