### ISSUE TITLE
CR-745-implement Filter with Custom Invoice wise and IRN Date wise

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#415]
implement Filter with Custom Invoice wise and IRN Date wise in session tdisg8431m100 & add IRN No. & date also - Exports Commercial
--

**Comment by ravik200** [comment]
[Test Document for Implement Filter with Custom Invoice wise and IRN Date wise.docx](https://github.com/Isgec/ERPLN/files/5364075/Test.Document.for.Implement.Filter.with.Custom.Invoice.wise.and.IRN.Date.wise.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam Solution GH415CR745_000 exported, Please move to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live working fine. Please close
