### ISSUE TITLE
CR772-Modifications in ERP Indenting Process for New codified Items

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#420]
Modifications in ERP Indenting Process for New codified Raw Material Items(Engineering)

**Comment by veena-isgec** [comment]
Modifications in ERP Indenting Process for New codified Raw Material and Boughtout items

**Comment by ravik200** [comment]
[Test Document for Modifications in ERP Indenting Process for New codified Raw Material Items.docx](https://github.com/Isgec/ERPLN/files/5444148/Test.Document.for.Modifications.in.ERP.Indenting.Process.for.New.codified.Raw.Material.Items.docx)
Test Document

**Comment by veena-isgec** [comment]
[CR772-GH420-Testing checklist-Modifications in ERP Indenting Process for New codified Raw Material Items.xlsx](https://github.com/Isgec/ERPLN/files/5444606/CR772-GH420-Testing.checklist-Modifications.in.ERP.Indenting.Process.for.New.codified.Raw.Material.Items.xlsx)

@Pankaj9583 please download attached testing check list and prepare testing document.

**Comment by Pankaj9583** [comment]
[CR772-Modifications in ERP Indenting Process for New codified Items-420.docx](https://github.com/Isgec/ERPLN/files/5449716/CR772-Modifications.in.ERP.Indenting.Process.for.New.codified.Items-420.docx)
Testing done and its working fine (Testing document attached for you reference)

**Comment by ravik200** [comment]
@Pankaj9583 sir, all bug fixed in test server please test again.

**Comment by Pankaj9583** [comment]
Scenario1 -Working fine, Scenario2 -Working fine, Scenario3 -Working fine
[Uploading CR772-GH420-Testing.checklist-Modifications.in.ERP.Indenting.Process.for.New.codified.Raw.Material.Items.xlsx…]()
(Testing document attached for you reference)

**Comment by veena-isgec** [comment]
@ravik200 tested ok, please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
