### ISSUE TITLE
CR765- Delivery date on Child Item Tracking History

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#421]
CR765- Delivery date on Child Item Tracking History

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.

**Comment by Pankaj9583** [comment]
[CR765- Delivery date on Child Item Tracking History.xlsx](https://github.com/Isgec/ERPLN/files/5400850/CR765-.Delivery.date.on.Child.Item.Tracking.History.xlsx)
Testing done and and its working fine (Document attached)

**Comment by veena-isgec** [comment]
@ravik200 tested ok, Please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam Moved to live, Please check.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
