### ISSUE TITLE
CR753-Sale Reversal

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#422]
CR753-Sale Reversal

**Comment by ravik200** [comment]
[Uploading Test Document for Sale Reversal.docx…]()
Test Document

**Comment by ravik200** [comment]
[Test Document for Sale Reversal.docx](https://github.com/Isgec/ERPLN/files/5422025/Test.Document.for.Sale.Reversal.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 test ok, please move to live

**Comment by veena-isgec** [comment]
@Pankaj9583 please test the changes done in negative invoice print. Also check that Positive invoice print should not be distrubed.

**Comment by Pankaj9583** [comment]
Tes
[Uploading CR753-Sale Reversal github 422.xlsx…]()
ting done and working fine. (Testing document attached )

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
