### ISSUE TITLE
CR770-Exports Dr/Credit Notes , GST Paid Invoices and its accounting

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#423]
CR770-Exports Dr/Credit Notes , GST Paid Invoices and its accounting

**Comment by veena-isgec** [comment]
under testing by Accounts

**Comment by veena-isgec** [comment]
UAT mail received from Pawan on 25 March 2021 13:59

**Comment by veena-isgec** [comment]
@ravik200 chnages have been moved to live, please update github

**Comment by ravik200** [comment]
@veena-isgec mam, github updated.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
