### ISSUE TITLE
CR762-TCS in IR Extension

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#424]
CR762-TCS in IR Extension

**Comment by veena-isgec** [comment]
@Pankaj9583 please test

**Comment by Pankaj9583** [comment]
[CR762-TCS in IR Extension.xlsx](https://github.com/Isgec/ERPLN/files/5408657/CR762-TCS.in.IR.Extension.xlsx)
Testing done and working fine (testing document attached)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
