### ISSUE TITLE
CR761-TCS in Warehouse and Purchase Receipt Print

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#425]
CR761-TCS in Warehouse and Purchase Receipt Print

**Comment by veena-isgec** [comment]
@Pankaj9583 please test

**Comment by Pankaj9583** [comment]
[CR761-TCS in Warehouse and Purchase Receipt Print.xlsx](https://github.com/Isgec/ERPLN/files/5413175/CR761-TCS.in.Warehouse.and.Purchase.Receipt.Print.xlsx)
Testing done and working fine (Testing document attached)

**Comment by veena-isgec** [comment]
@ravik200 tested ok, please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
