### ISSUE TITLE
CR764 Delivery Challan Report

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#428]
CR764 Delivery Challan Report

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.
![image](https://user-images.githubusercontent.com/43699482/96955618-a8790f00-1513-11eb-91c8-593fda0a2dee.png)
![image](https://user-images.githubusercontent.com/43699482/96955631-b333a400-1513-11eb-8318-6590d518d4bd.png)

**Comment by veena-isgec** [comment]
@ravik200 Linked Receipt should be the Receipt on which delivery challan is created, presently report is showing receipt 

![image](https://user-images.githubusercontent.com/43699482/96957458-4bcc2300-1518-11eb-80cc-ff23e57274a1.png)

**Comment by ravik200** [comment]
@veena-isgec mam Moved to live, please check.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
