### ISSUE TITLE
CR754-Process of GST Paid Invoices Dr Notes/Cr Notes of Export Invoicing 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#429]
CR754-Process of GST Paid Invoices Dr Notes/Cr Notes of Export Invoicing

**Comment by ravik200** [comment]
@veena-isgec mam, Solution GH429CR754_000 is created Please move to live.

**Comment by veena-isgec** [comment]
@ravik200 solution moved to live, please update github scripts.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
