### ISSUE TITLE
CR781-Correction in Remittance Letter Report

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#430]
In case of inter company payment against purchase transaction, PO no., IR no. and project code in "Remittance Letter-tfisg2400m009" picks from co.200 for the same document no. instead of the co. of purchase Transactions.
--

**Comment by ravik200** [comment]
[Test Document for Correction in Remittance Letter Report.docx](https://github.com/Isgec/ERPLN/files/5473774/Test.Document.for.Correction.in.Remittance.Letter.Report.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test the report for 200 company and other than 200 company remittance letters.

**Comment by Pankaj9583** [comment]
[CR781-Correction in Remittance Letter Report.xlsx](https://github.com/Isgec/ERPLN/files/5487419/CR781-Correction.in.Remittance.Letter.Report.xlsx)
Testing done and working fine. (Document attached)

**Comment by veena-isgec** [comment]
Got verbal confirmation from Saha ji today to move this to live. My revert mail is dated 07 November 2020 11:05

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by veena-isgec** [comment]
[testing doc of Remittence letter.docx](https://github.com/Isgec/ERPLN/files/5572959/testing.doc.of.Remittence.letter.docx)

**Comment by veena-isgec** [comment]
@ravik200 tested ok for all payments. Please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
