### ISSUE TITLE
CR774-Print Warehouse codes in Po Delivery Reports

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#431]
Different warehouse codes are used in case material is dispatched to a location other than project site. Hence, if warehouse code is visible in PO Delivery Reports it can easily be identified as to which receipt needs to be billed and which one needs to be marked as FIV.
Column of Warehouse should be added in below reports:
1) Print PO Delivery Status [Detailed] - tdisg4401m200 &
2) PO Line wise Delivery Status - tdisg4401m300

**Comment by ravik200** [comment]
[Test Document for Print Warehouse codes in Po Delivery Reports.docx](https://github.com/Isgec/ERPLN/files/5474282/Test.Document.for.Print.Warehouse.codes.in.Po.Delivery.Reports.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test the report.

**Comment by Pankaj9583** [comment]
Testing done & warehouse code showing in Print PO Delivery Status [Detailed] - tdisg4401m200 & PO Line wise Delivery Status - tdisg4401m300 (Testing document attached for your
[CR774-Print Warehouse codes in Po Delivery Reports.xlsx](https://github.com/Isgec/ERPLN/files/5474524/CR774-Print.Warehouse.codes.in.Po.Delivery.Reports.xlsx)
 reference)

**Comment by veena-isgec** [comment]
UAT mail received from Sandeep Sharma on 03 November 2020 09:27

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
