### ISSUE TITLE
CR748-Manual Invoice, Debit Note, Credit Note in Report "Summary of Invoice Register"

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#434]
CR748-Manual Invoice, Debit Note, Credit Note in Report "Summary of Invoice Register"

**Comment by ravik200** [comment]
[Test Document for Manual Invoice Summary of Invoice Register.docx](https://github.com/Isgec/ERPLN/files/5509685/Test.Document.for.Manual.Invoice.Summary.of.Invoice.Register.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 Please move to live for further testing.

**Comment by ravik200** [comment]
@veena-isgec mam, Solution GH433CR747_000 is exported from Server 37, Please move to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
