### ISSUE TITLE
CR775-Engineering-Manual selection of Approver/Reviewer to be restricted if person is not authorized for the same

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#436]
DCR raised for issue :- If Approving/Reviewing authority is not enabled for an activity to the selected user, user should not be allowed to select his name in the system manually enter and Process the Drawing/Document to avoid such issues for back end correction by IT.

Please note the below session for your further action.

1 dmisg0101m200 Document Submission Functionality for Reviewer/Approver Assign.
2 dmisg0101m300 Document Review Functionality for Approver Assign.
3 dmisg1114m000 DCR Session for Approver Assign.

**Comment by ravik200** [comment]
@veena-isgec mam, Done in test and live both.

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
