### ISSUE TITLE
CR794-Modification in Accounts Credit Note E Invoicing functionality

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#437]
CR794-Modification in Accounts Credit Note E Invoicing functionality

**Comment by veena-isgec** [comment]
[CR794-Modification in Accounts Credit Note E Invoicing functionality #437.xlsx](https://github.com/Isgec/ERPLN/files/5508832/CR794-Modification.in.Accounts.Credit.Note.E.Invoicing.functionality.437.xlsx)

**Comment by ravik200** [comment]
[Test Document for Modification in Accounts Credit Note E Invoicing functionality.docx](https://github.com/Isgec/ERPLN/files/5510461/Test.Document.for.Modification.in.Accounts.Credit.Note.E.Invoicing.functionality.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 Pls move to live for further testing.

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
