### ISSUE TITLE
CR778-Correction in PO Register for Audit

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#438]
Correction in PO Register for Audit (CR778)

**Comment by veena-isgec** [comment]
[Uploading CR778-Correction in PO Register for Audit #438.xlsx…]()

**Comment by veena-isgec** [comment]
@ravik200 please update status of CR

**Comment by ravik200** [comment]
[Test Document for Correction in PO Register for Audit.docx](https://github.com/Isgec/ERPLN/files/5551665/Test.Document.for.Correction.in.PO.Register.for.Audit.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, Test Document uploaded please check

**Comment by veena-isgec** [comment]
UAT Mail received from Kamal on 01 December 2020 12:35

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
