### ISSUE TITLE
IR-158545-PTR print project code not printing in 700 company

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#439]
158545-Please refer Batch no:1982 and 1990(CO:700) . In PTR print I am unable to see Project code. (Print Voucher details-tfisg1402m100)

**Comment by ravik200** [comment]
[Test Document for IR 158545 PTR print project code not printing in 700 company.docx](https://github.com/Isgec/ERPLN/files/5559692/Test.Document.for.IR.158545.PTR.print.project.code.not.printing.in.700.company.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test this github.

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live, please close.
