### ISSUE TITLE
IR158124-Payment term is showing in negative in PO

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#440]
158124-Payment term is showing in negative in PO

**Comment by ravik200** [comment]
[Test Document for Payment term is showing in negative in PO.docx](https://github.com/Isgec/ERPLN/files/5571711/Test.Document.for.Payment.term.is.showing.in.negative.in.PO.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test this github

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test this github

**Comment by Pankaj9583** [comment]
Testing done and its working file (testing document attached)
[158124-Payment term is showing in negative in PO_440.docx](https://github.com/Isgec/ERPLN/files/6309794/158124-Payment.term.is.showing.in.negative.in.PO_440.docx)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, Moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
