### ISSUE TITLE
158843-Utility for handling support calls of creating multiple receipts with same IRN

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#441]
158843-Please authorized User-330,3776 & 9583 for create & Confirm ware house and purchase receipt with same IR no.
Above utility will be used only by BaaN Support after receiving approval by Accounts.

**Comment by ravik200** [comment]
[Test Document for Utility for handling support calls of creating multiple receipts with same IRN.docx](https://github.com/Isgec/ERPLN/files/5564533/Test.Document.for.Utility.for.handling.support.calls.of.creating.multiple.receipts.with.same.IRN.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec , @Pankaj9583 moved to live and utility table are whisg000

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
