### ISSUE TITLE
CR777-Functionality for GST defaulters Suppliers

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#442]
Functionality for GST defaulters Suppliers

**Comment by veena-isgec** [comment]
[CR777-Functionality for GST defaulters Suppliers #442.xlsx](https://github.com/Isgec/ERPLN/files/5577035/CR777-Functionality.for.GST.defaulters.Suppliers.442.xlsx)

**Comment by ravik200** [comment]
[Test Document for Functionality for GST defaulters Suppliers.docx](https://github.com/Isgec/ERPLN/files/5588667/Test.Document.for.Functionality.for.GST.defaulters.Suppliers.docx)
Test Document

**Comment by veena-isgec** [comment]
Being handled through #529
