### ISSUE TITLE
CR706-Payment register

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#445]
CR706-Payment register

**Comment by veena-isgec** [comment]
@ravik200 please create session for following link in live server

http://reposrv01/Reports/Pages/Report.aspx?ItemPath=%2fP_DrawingwiseWeightReport

**Comment by ravik200** [comment]
![image](https://user-images.githubusercontent.com/56112454/104688743-4c471500-5727-11eb-93eb-a3691471c9cd.png)
New Session dmisg0001m000 created.

**Comment by ravik200** [comment]
Session dmisg0001m000 created.

**Comment by veena-isgec** [comment]
Sorry above session was for CR805, by mistake commented in this CR

**Comment by veena-isgec** [comment]
@ravik200 please update status of this Github

**Comment by ravik200** [comment]
@veena-isgec mam, Session tfisg0000m000 created.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
