### ISSUE TITLE
Checks on Custom inv selection in exports dr cr note

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#446]

**Comment by veena-isgec** [comment]
1. Custom inv should have been e invoiced
2. custom invoice should not hv commercial inv generated
3. Billing advice should not be in returned  to projects status

**Comment by ravik200** [comment]
@veena-isgec mam, Done in all servers

**Comment by veena-isgec** [comment]
@hariharan-isgec done on test and live both , please close
