### ISSUE TITLE
CR757-Blacklisting of vendor should not affect Bill booking and amendments of existing POs

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#447]
Blacklisting of vendor should not affect Bill booking of existing POs

**Comment by veena-isgec** [comment]
Blacklisting of vendor should not affect Bill booking and amendments of existing POs. New line in existing POs can be added.

**Comment by ravik200** [comment]
[Test Document for Blacklisting of vendor should not affect Bill booking and amendments of existing POs.docx](https://github.com/Isgec/ERPLN/files/5614179/Test.Document.for.Blacklisting.of.vendor.should.not.affect.Bill.booking.and.amendments.of.existing.POs.docx)
Test Document

**Comment by Pankaj9583** [comment]
[CR757-Blacklisting of vendor should not affect Bill booking and amendments of existing POs.docx](https://github.com/Isgec/ERPLN/files/5616075/CR757-Blacklisting.of.vendor.should.not.affect.Bill.booking.and.amendments.of.existing.POs.docx)
Testing done & working fine

**Comment by veena-isgec** [comment]
@ravik200 tested ok, please move to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
