### ISSUE TITLE
CR784-PO, Project, Buyer required in GSTR2 data generation

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#449]
Purchase order no., Project code and user code and description of person preparing PO (Buyer of Internal Contacts) required in GSTR2 / RCM data - tfisg4515m000.

**Comment by ravik200** [comment]
[Test Document for PO.docx](https://github.com/Isgec/ERPLN/files/5622562/Test.Document.for.PO.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 Please move to live for further testing. As this functionality is independent and do not affect the other business process.

**Comment by veena-isgec** [comment]
UAT Mail received from Pawan after testing in live on 02 December 2020 14:29

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close
