### ISSUE TITLE
CR803-Please print transaction reference in Debit Credit Note(Non GST) print

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#450]
Particulars comes from Transaction Text in printing customer debit / credit note from session “tfisg2400m013”. Please print transaction reference also from table tfgld102 or tfgld106 below the transaction tax.

**Comment by ravik200** [comment]
[Test Document for print transaction reference in Debit Credit Note.docx](https://github.com/Isgec/ERPLN/files/5640772/Test.Document.for.print.transaction.reference.in.Debit.Credit.Note.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by veena-isgec** [comment]
@Pankaj9583 Please check.

**Comment by Pankaj9583** [comment]
[CR803-Please print transaction reference in Debit Credit Note Non GST print 450.docx](https://github.com/Isgec/ERPLN/files/5718891/CR803-Please.print.transaction.reference.in.Debit.Credit.Note.Non.GST.print.450.docx)
Testing done and its working fine (Testing document attached)

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
