### ISSUE TITLE
IR159733-Exclude WHR correction session from Purchase Receipt blocking on month end

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#451]
IR159733-Exclude WHR correction session from Purchase Receipt blocking on month end

**Comment by ravik200** [comment]
[Test Document for Exclude WHR correction session from Purchase Receipt blocking on month end.docx](https://github.com/Isgec/ERPLN/files/5634008/Test.Document.for.Exclude.WHR.correction.session.from.Purchase.Receipt.blocking.on.month.end.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, Moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
