### ISSUE TITLE
CR-692 Auto assignment of advance from Quick PTR session

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#452]
CR-692 Auto assignment of advance from Quick PTR session

**Comment by veena-isgec** [comment]
Linking of DR CR Note with Commercial Invoice and its Accounting while processing of commercial invoice has been tested multiple times by Techvikas and myself. its working fine so this part can be moved to live.

A utility which will do accounting of GST Paid Invoices and linked DR CR notes is still under development

**Comment by veena-isgec** [comment]
Techvikas is preparing for Live

**Comment by veena-isgec** [comment]
@ravik200 this customisation has been moved to live by Techvikas, please update github.

**Comment by veena-isgec** [comment]
@ravik200 solution is GH452CR692_000

**Comment by ravik200** [comment]
@veena-isgec mam, github updated.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
