### ISSUE TITLE
158492-Session  Review SAR is very slow. It takes 5-10 minutes time to upload for some projects. 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#453]
158492-My BAAN system for “Review SAR” tab is very slow. It takes 5-10 minutes time to upload.

session tpisg0574m200-Review SAR

**Comment by ravik200** [comment]
[Test Document for Session Review SAR is very slow.docx](https://github.com/Isgec/ERPLN/files/5635741/Test.Document.for.Session.Review.SAR.is.very.slow.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, Moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
