### ISSUE TITLE
Remove decimal check from billing advice(E-Invoicing)

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#454]
From: Parmanand Ranakoti [mailto:parmanand.ranakoti@isgec.co.in] 
Sent: 09 December 2020 08:22
To: 'Veena'
Cc: hariharan.m@isgec.co.in; chander.parkash@isgec.co.in; 'Alok Kaura'
Subject: RE: Decimal limits in E-Invoicing

Madam,

As discussed, considering practical difficulties of Projects, remove the check and continue the practice which you followed earlier. Since the total Invoice value remain unchanged, the minor variation arising out of the decimals restricted upto 3 is explainable. 

I hope it is clear.

Regards,

Parmanand Ranakoti

From: Veena [mailto:veena@isgec.co.in] 
Sent: 08 December 2020 18:04
To: 'Parmanand Ranakoti'
Cc: hariharan.m@isgec.co.in; chander.parkash@isgec.co.in; 'Alok Kaura'
Subject: Decimal limits in E-Invoicing

Sir,

Please refer to our discussion regarding subject matter.

E-Invoicing system allows maximum 3 decimals in Quantity and Price fields.  In Isgec Sale Invoices(domestic and exports both), Price is calculated as Billing value/Quantity, which many times returns more than 3 decimals. Rounding off cannot be done because in that case reverse calculation of Sale Invoice Amount(Qty*Price) not matches the taxable amount. 

Hence we have put a check that system will not allow to create Sale invoice(domestic and exports both) if Billing value/Packing List Qty returns more than 3 decimals. But projects people are facing issue due to this check because Customer Billing breakup amount is fixed and cannot be changed to comply decimals. 

Please confirm whether this check should be continued or removed. 

Thanks & Regards

Veena
IT & Systems

**Comment by ravik200** [comment]
[Test Document for Remove decimal check from billing advice.docx](https://github.com/Isgec/ERPLN/files/5706984/Test.Document.for.Remove.decimal.check.from.billing.advice.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, removed check in all the servers.

**Comment by veena-isgec** [comment]
Moved to live. Working fine.
