### ISSUE TITLE
IR160703- IGST Amount not showing in  GSTR-1 Report

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#455]
160703- Custom invoices have been raised from Maharashtra with IGST; But IGST Amount not showing in  GSTR-1 Report session"ciisg2405m200".

**Comment by ravik200** [comment]
[Test Document for IGST Amount not showing in GSTR.docx](https://github.com/Isgec/ERPLN/files/5734832/Test.Document.for.IGST.Amount.not.showing.in.GSTR.docx)
Test Document

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
