### ISSUE TITLE
CR805-New Drawing wise weight report required thru BAAN

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#456]
New Drawing wise weight report required thru BAAN
Following Heads are required in the report:-

1. Drawing Number
2. Drawing Title
3. Revision Number
4. Drawing Status
5. Release Date
6. Weight

**Comment by veena-isgec** [comment]
@ravik200 please create session for following link in live server

http://reposrv01/Reports/Pages/Report.aspx?ItemPath=%2fP_DrawingwiseWeightReport

**Comment by ravik200** [comment]
Session dmisg0001m000 created.

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live working fine. Please close the case.
