### ISSUE TITLE
CR795-Modification in Print Voucher

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#457]
Modification in Print Voucher

**Comment by ravik200** [comment]
[Test Document for Modification in Print Voucher.docx](https://github.com/Isgec/ERPLN/files/5723630/Test.Document.for.Modification.in.Print.Voucher.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please upload test document.

**Comment by Pankaj9583** [comment]
[IR.docx](https://github.com/Isgec/ERPLN/files/5734803/IR.docx)
Testing done and its working fine. Document attached for you reference.

**Comment by veena-isgec** [comment]
UAT mail received from Pawan on 25 January 2021 11:11

**Comment by veena-isgec** [comment]
@ravik200 please move o live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
