### ISSUE TITLE
CR355-Facility to maintain multiple Isgec Drawings Numbers against single receipt.

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#458]
CR355-Facility to maintain multiple Isgec Drawings Numbers against single receipt.

**Comment by ravik200** [comment]
[Test Document for Facility to maintain multiple Isgec  Drawings Numbers against single receipt.docx](https://github.com/Isgec/ERPLN/files/5750414/Test.Document.for.Facility.to.maintain.multiple.Isgec.Drawings.Numbers.against.single.receipt.docx)
Test Document

**Comment by ravik200** [comment]
[Test Document for Facility to maintain multiple Isgec  Drawings Numbers against single receipt.docx](https://github.com/Isgec/ERPLN/files/5855215/Test.Document.for.Facility.to.maintain.multiple.Isgec.Drawings.Numbers.against.single.receipt.docx)
RE Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Rajesh Vashist on 05 February 2021 19:29

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
