### ISSUE TITLE
Modification in Export Custom DR CR Note Entry and generation sessions

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#459]
1. Tax code should be same as Preceding custom Invoice and non editable
2. HSN Code and description should be same as in corresponding line of custom invoice  and will remain non editable here
3. DBK Serial No. and description should be same as in corresponding line of custom invoice  and will remain non editable here

For point 2 & 3 correction to be done in HTML print of DR CR notes also

**Comment by ravik200** [comment]
[Test Document Custom Invoice Report.docx](https://github.com/Isgec/ERPLN/files/5724177/Test.Document.Custom.Invoice.Report.docx)
Test Document

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
