### ISSUE TITLE
CR823-Correction in CIN and PAN No. on Sale Invoice

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#460]
Correction in CIN and PAN No. on Sale Invoice requested by Accounts approved by commercial
--

**Comment by ravik200** [comment]
[Test Document for Correction in CIN and PAN No.docx](https://github.com/Isgec/ERPLN/files/5734837/Test.Document.for.Correction.in.CIN.and.PAN.No.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, Correction done in all the servers.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
