### ISSUE TITLE
160241- Project Currency has been mentioned Euro but it is being printed as USD in Custom invoice.

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#461]
160241- Project Currency has been mentioned Euro but it is being printed as USD in Custom invoice.

**Comment by ravik200** [comment]
[Test Document for Project Currency has been mentioned Euro but it is being printed as USD in Custom invoice.docx](https://github.com/Isgec/ERPLN/files/5734957/Test.Document.for.Project.Currency.has.been.mentioned.Euro.but.it.is.being.printed.as.USD.in.Custom.invoice.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, Fixed in all server.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
