### ISSUE TITLE
CR734-Modififcation in bank payment on Banks portal session

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#462]
CR734-Modififcation in bank payment on Banks portal session

**Comment by veena-isgec** [comment]
[Uploading CR734-Modififcation in bank payment on Banks portal session #462.xlsx…]()

**Comment by veena-isgec** [comment]
[CR734-Modififcation in bank payment on Banks portal session #462.xlsx](https://github.com/Isgec/ERPLN/files/5745999/CR734-Modififcation.in.bank.payment.on.Banks.portal.session.462.xlsx)

**Comment by ravik200** [comment]
[Test Document for Modification in bank payment on Banks portal session.docx](https://github.com/Isgec/ERPLN/files/5753717/Test.Document.for.Modification.in.bank.payment.on.Banks.portal.session.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
