### ISSUE TITLE
CR815-our office work hours will change from 1st January 2021

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#464]
our office work hours will change from 1st January 2021

**Comment by ravik200** [comment]
[Test Document for our office work hours will change from 1st January 2021 in Man Hours Transaction.docx](https://github.com/Isgec/ERPLN/files/5756521/Test.Document.for.our.office.work.hours.will.change.from.1st.January.2021.in.Man.Hours.Transaction.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Rajesh on 31 December 2020 17:01, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
