### ISSUE TITLE
CR-832-Price annexure upload with PO

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#465]
From: Ajay Gupta [mailto:ajay.gupta@isgec.co.in] 
Sent: 28 December 2020 11:03
To: hariharan.m@isgec.co.in; veena@isgec.co.in
Subject: Price annexure uploading with PO

Sir/ Madam
Format for Price annexure to be uploaded with PO was asked.
Currently, buyer is giving Item name, quantity, unit, rate and value in text field.
Therefore, same information can be provided in price annexure.
Besides above information, item code is another field which is desirable but buyer does not have this information while writing in text.

Regards
Ajay Gupta

**Comment by ravik200** [comment]
[Test Document for Price annexure upload with PO.docx](https://github.com/Isgec/ERPLN/files/5770014/Test.Document.for.Price.annexure.upload.with.PO.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Mr. Ajay Gupta on 24 January 2021 16:16

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, For new table and sessions Solution GH465CR832_000 created in server 37, Please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, Moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
