### ISSUE TITLE
CR818-Supplier Debit note entry in system

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#466]
CR818-Supplier Debit note entry in system

**Comment by ravik200** [comment]
[Test Document for Supplier Debit note entry in system.docx](https://github.com/Isgec/ERPLN/files/5800782/Test.Document.for.Supplier.Debit.note.entry.in.system.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Mr. Ajay Gupta on 29 January 2021 20:23

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
