### ISSUE TITLE
IR160750-Billing advice line cannot be delete after done Custom invoice and E-Invoicing

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#467]
IR160750-Billing advice line cannot be delete after done Custom invoice and E-Invoicing

**Comment by ravik200** [comment]
[Test Document for Billing advice line cannot be delete after done Custom invoice and E.docx](https://github.com/Isgec/ERPLN/files/5763479/Test.Document.for.Billing.advice.line.cannot.be.delete.after.done.Custom.invoice.and.E.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
