### ISSUE TITLE
CR830-Modification in custom invoice print format for RoDTEP

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#468]
From: Baan Support Team-Isgec [mailto:baansupport@isgec.co.in] 
Sent: 04 January 2021 15:49
To: 'Chander parkash'; 'Veena'
Cc: ''sudhir kumar nathani''; 'Alok Kaura 2'; ravi.kumar2@isgec.co.in; 'Suraj Bhandari'; exportdocs@isgec.co.in
Subject: RE: [exportdocs] RE: RoDTEP in Place of MEIS Urgent

Needful done in live sever (custom invoice)

Regards 
Baan Support Team
IT & System
 
A-8, Sector 63, Second Floor
Noida -201301 (UP)
0120-4085500, Extn No:- 7219
 Every 3000 sheets of paper cost us a tree. Let's consider our environmental responsibility before printing this e-mail - Save paper

From: Chander parkash [mailto:chander.parkash@isgec.co.in] 
Sent: 04 January 2021 15:32
To: 'Baan Support Team-Isgec'; 'Veena'
Cc: ''sudhir kumar nathani''; 'Alok Kaura 2'; ravi.kumar2@isgec.co.in; 'Suraj Bhandari'; exportdocs@isgec.co.in
Subject: RE: [exportdocs] RE: RoDTEP in Place of MEIS Urgent

Okay… Go Ahead..  

Thanks & Regards 

Chander  Parkash
 
A-4,Sector-24,
Noida-201301,India
Direct No. : +91-120-4085129
Mobile No. : +91-99713-98866
Fax: +91-120-4085100
Web: www.isgec.com
----Kindly Wear Mask,Maintain Social Distancing and Wash Your Hands Regularly-----

From: exportdocs-request@isgec.co.in [mailto:exportdocs-request@isgec.co.in] On Behalf Of Baan Support Team-Isgec
Sent: Monday, January 04, 2021 3:23 PM
To: 'Chander parkash'; 'Veena'
Cc: ''sudhir kumar nathani''; 'Alok Kaura 2'; ravi.kumar2@isgec.co.in; 'Suraj Bhandari'; exportdocs@isgec.co.in
Subject: RE: [exportdocs] RE: RoDTEP in Place of MEIS Urgent

Please check again in test server and confirm

Regards 
Baan Support Team
IT & System
 
A-8, Sector 63, Second Floor
Noida -201301 (UP)
0120-4085500, Extn No:- 7219
 Every 3000 sheets of paper cost us a tree. Let's consider our environmental responsibility before printing this e-mail - Save paper

From: Chander parkash [mailto:chander.parkash@isgec.co.in] 
Sent: 04 January 2021 14:50
To: 'Baan Support Team-Isgec'; 'Veena'
Cc: ''sudhir kumar nathani''; 'Alok Kaura 2'; ravi.kumar2@isgec.co.in; 'Suraj Bhandari'; exportdocs@isgec.co.in
Subject: RE: [exportdocs] RE: RoDTEP in Place of MEIS Urgent

Kindly maintain proper space gap/// 

WE INTEND TO CLAIM REWARDS UNDER REMISSION OF DUTIES AND TAXES ON EXPORTED PRODUCTS (RoDTEP) SCHEME. 

ALSO REWARD SCHEME MUST BE TICKED YES

Thanks & Regards 

Chander  Parkash
 
A-4,Sector-24,
Noida-201301,India
Direct No. : +91-120-4085129
Mobile No. : +91-99713-98866
Fax: +91-120-4085100
Web: www.isgec.com
----Kindly Wear Mask,Maintain Social Distancing and Wash Your Hands Regularly-----

From: Chander parkash [mailto:chander.parkash@isgec.co.in] 
Sent: Monday, January 04, 2021 2:08 PM
To: 'Baan Support Team-Isgec'; 'Veena'
Cc: ''sudhir kumar nathani''; 'Alok Kaura 2'; 'ravi.kumar2@isgec.co.in'; 'Suraj Bhandari'; 'exportdocs@isgec.co.in'
Subject: RE: [exportdocs] RE: RoDTEP in Place of MEIS Urgent

Here is the desired invoice for your ready reference..   

 

Thanks & Regards 

Chander  Parkash
 
A-4,Sector-24,
Noida-201301,India
Direct No. : +91-120-4085129
Mobile No. : +91-99713-98866
Fax: +91-120-4085100
Web: www.isgec.com
----Kindly Wear Mask,Maintain Social Distancing and Wash Your Hands Regularly-----

From: exportdocs-request@isgec.co.in [mailto:exportdocs-request@isgec.co.in] On Behalf Of Baan Support Team-Isgec
Sent: Monday, January 04, 2021 1:16 PM
To: 'Chander parkash'; 'Veena'
Cc: ''sudhir kumar nathani''; 'Alok Kaura 2'; ravi.kumar2@isgec.co.in; 'Suraj Bhandari'; exportdocs@isgec.co.in
Subject: [exportdocs] RE: RoDTEP in Place of MEIS Urgent
Importance: High

Please share invoice ASAP.

Regards 
Baan Support Team
IT & System
 
A-8, Sector 63, Second Floor
Noida -201301 (UP)
0120-4085500, Extn No:- 7219
 Every 3000 sheets of paper cost us a tree. Let's consider our environmental responsibility before printing this e-mail - Save paper

From: Baan Support Team-Isgec [mailto:baansupport@isgec.co.in] 
Sent: 04 January 2021 10:54
To: 'Chander parkash'; 'Veena'
Cc: ''sudhir kumar nathani''; 'Alok Kaura 2'; 'ravi.kumar2@isgec.co.in'; 'Suraj Bhandari'; 'exportdocs@isgec.co.in'
Subject: RE: RoDTEP in Place of MEIS Urgent 

As discuss with please share invoice 

Regards 
Baan Support Team
IT & System
 
A-8, Sector 63, Second Floor
Noida -201301 (UP)
0120-4085500, Extn No:- 7219
 Every 3000 sheets of paper cost us a tree. Let's consider our environmental responsibility before printing this e-mail - Save paper

From: Chander parkash [mailto:chander.parkash@isgec.co.in] 
Sent: 04 January 2021 10:25
To: 'Veena'
Cc: ''sudhir kumar nathani''; Baan Support; 'Alok Kaura 2'; ravi.kumar2@isgec.co.in; 'Suraj Bhandari'; exportdocs@isgec.co.in
Subject: RE: RoDTEP in Place of MEIS Urgent 

Following declaration to be incorporated in Commercial Invoice Only.  

WE INTEND TO CLAIM REWARDS UNDER REMISSION OF DUTIES AND TAXES ON EXPORTED PRODUCTS (RoDTEP) SCHEME. ALSO REWARD SCHEME MUST BE TICKED YES

Thanks & Regards 

Chander  Parkash
 
A-4,Sector-24,
Noida-201301,India
Direct No. : +91-120-4085129
Mobile No. : +91-99713-98866
Fax: +91-120-4085100
Web: www.isgec.com
----Kindly Wear Mask,Maintain Social Distancing and Wash Your Hands Regularly-----

From: Chander parkash [mailto:chander.parkash@isgec.co.in] 
Sent: Saturday, January 02, 2021 4:53 PM
To: 'Veena' (veena@isgec.co.in)
Cc: ''sudhir kumar nathani' (sudhir.nathani@isgec.co.in)'; Baan Support (baansupport@isgec.co.in); 'Alok Kaura 2' (alokkaura@isgec.co.in); ravi.kumar2@isgec.co.in; 'Suraj Bhandari' (suraj.bhandari@isgec.co.in); exportdocs@isgec.co.in
Subject: RoDTEP in Place of MEIS Urgent 

URGENT 

Hi Ma’am

Good Day !!

Would like to inform that RoDTEP Scheme has been implemented in place of MEIS Scheme. Now Please arrange to amend declaration as below:

WE INTEND TO CLAIM  “RoDTEP” 

in place of  

WE INTEND TO CLAIM REWARDS UNDER MERCHANDISE EXPORTS FROM INDIA SCHEME (MEIS)

Also in system , Kindly replace MEIS word with “RoDEP”

Other  Process is as usual.  

Thanks & Regards 

Chander  Parkash
 
A-4,Sector-24,
Noida-201301,India
Direct No. : +91-120-4085129
Mobile No. : +91-99713-98866
Fax: +91-120-4085100
Web: www.isgec.com
----Kindly Wear Mask,Maintain Social Distancing and Wash Your Hands Regularly-----

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live. Please close
