### ISSUE TITLE
IR164201 - 	Incorrect value in Report Print Audit Purchase Order Register order no. P83006915 (Print Purchase order Register) 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#469]
164201 - 	Incorrect value in Report Print Audit Purchase Order Register order no. P83006915 (Print Purchase order Register)

**Comment by ravik200** [comment]
[Test Document for Incorrect value in Report Print Audit Purchase Order Register order no.docx](https://github.com/Isgec/ERPLN/files/5780078/Test.Document.for.Incorrect.value.in.Report.Print.Audit.Purchase.Order.Register.order.no.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, fixed in all servers

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to Live please close.
