### ISSUE TITLE
164331-Estimate line launch sanction control should not allow again if sanction already transfer

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#471]
164331-Estimate line launch sanction control should not allow again if sanction already transfer

**Comment by veena-isgec** [comment]
@ravik200 @Pankaj9583 please takeup this github

**Comment by veena-isgec** [comment]
@ravik200 @Pankaj9583 please takeup this github

**Comment by ravik200** [comment]
[Test Document for Estimate line launch sanction control should not allow again if sanction already transfer.docx](https://github.com/Isgec/ERPLN/files/6276103/Test.Document.for.Estimate.line.launch.sanction.control.should.not.allow.again.if.sanction.already.transfer.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.

**Comment by Pankaj9583** [comment]
testing done and its working fine (Testing document attached)
[Uploading 164331-Estimate line launch sanction control should not allow again if sanction already transfer_ 471.docx…]()

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live , please close.
