### ISSUE TITLE
165944-New line disable in Billing advice after generate E-invoicing 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#475]
165944-New line disable in Billing advice after generate E-invoicing

**Comment by ravik200** [comment]
[Test Document for New line disable in Billing advice after generate E.docx](https://github.com/Isgec/ERPLN/files/5840159/Test.Document.for.New.line.disable.in.Billing.advice.after.generate.E.docx)

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
