### ISSUE TITLE
164594-Issue in E-Invoicing of Accounts Debit Note

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#476]
No, it is not, you just need to make sure that it is not passed in the JSON.

If it is passed, NIC expect some values in the same.

On Thu, Jan 21, 2021 at 3:48 PM Veena <veena@isgec.co.in> wrote:
But this is mandatory if invoice type is not INV.
 
From: Pranjal Singh [mailto:pranjalsingh@mastersindia.co] 
Sent: 21 January 2021 15:46
To: Lalit Gupta
Cc: Veena; mohinder pal singh; Parmanand Ranakoti; Baan Support; lalit gupta
Subject: Re: FW: Error in uploading CDN in e invoicing portal
 
Hello Mr. Lalit,
 
Please don't send below details in JSON.
 
    },
    "payment_details": null,
    "reference_details": {
        "invoice_remarks": "",
        "document_period_details": null,
        "preceding_document_details": [
            {
                "reference_of_original_invoice": "",
                "preceding_invoice_date": "",
                "other_reference": ""
            }
        ],
        "contract_details": null
    },
 
 
 
On Thu, Jan 21, 2021 at 3:41 PM Lalit Gupta <lalit.gupta@isgec.co.in> wrote:
 
{"access_token":"e2715d11ddf01b6267be112ca32b392c2f47f48d","user_gstin":"09AAACT5540K2Z4","data_source":"ERP","transaction_details":{"supply_type":"B2B","charge_type":"N","igst_on_intra":"N","ecommerce_gstin":""},"document_details":{"document_type":"DBN","document_number":"CDN41090003","document_date":"12/01/2021"},"seller_details":{"gstin":"09AAACT5540K2Z4","legal_name":"ISGEC HEAVY ENGINEERING LTD.","trade_name":"ISGEC HEAVY ENGINEERING LTD.","address1":"A-4, Sector-24,Noida,201301,UP","address2":"Telp : 0120-4085001, Fax : 012","location":"Noida","pincode":"201301","state_code":"09","phone_number":"","email":""},"buyer_details":{"gstin":"24AAACG5609C1Z5","legal_name":"GHCL Limited,","trade_name":"GHCL Limited,","address1":",Somnath,362275,GJ","address2":"Telp : , Fax :","location":"Somnath","pincode":"362275","place_of_supply":"24","state_code":"24","phone_number":"","email":""},"dispatch_details":null,"ship_details":null,"export_details":{"ship_bill_number":"","ship_bill_date":"01/01/1970 05:30:00","country_code":"","foreign_currency":"","refund_claim":"N","port_code":"","export_duty":"0.00"},"payment_details":null,"reference_details":{"invoice_remarks":"","document_period_details":null,"preceding_document_details":[{"reference_of_original_invoice":"","preceding_invoice_date":"","other_reference":""}],"contract_details":null},"additional_document_details":null,"value_details":{"total_assessable_value":"42865","total_cgst_value":"0","total_sgst_value":"0","total_igst_value":"7715.7","total_cess_value":"0","total_cess_value_of_state":"0","total_discount":"0.00","total_other_charges":"0.00","total_invoice_value":"50580.7","round_off_amount":"0.00","total_invoice_value_additional_currency":"50580.7"},"ewaybill_details":{"transporter_id":"","transporter_name":"","transportation_mode":"","transportation_distance":"","transporter_document_number":"","transporter_document_date":"","vehicle_number":"","vehicle_type":""},"item_list":[{"item_serial_number":"1","product_description":"Claim for Freight Charges","is_service":"Y","hsn_code":"9965","bar_code":"","quantity":"1","free_quantity":"0","unit":"NOS","unit_price":"42865","total_amount":"42865","pre_tax_value":"0","discount":"0","other_charge":"0","assessable_value":"42865","gst_rate":"18","igst_amount":"7715.7","cgst_amount":"0","sgst_amount":"0","cess_rate":"0","cess_amount":"0","cess_nonadvol_amount":"0","state_cess_rate":"0","state_cess_amount":"0","state_cess_nonadvol_amount":"0","total_item_value":"50580.7","country_origin":"","order_line_reference":"","product_serial_number":"","batch_details":{"name":"","expiry_date":"01/01/1970","warranty_date":"01/01/1970"},"attribute_details":[{"item_attribute_details":"","item_attribute_value":""}]}]}
 
 
From: Veena [mailto:veena@isgec.co.in] 
Sent: 21 January 2021 14:32
To: 'Pranjal Singh'
Cc: 'mohinder pal singh'; 'Parmanand Ranakoti'; 'Baan Support'; 'lalit gupta'
Subject: RE: FW: Error in uploading CDN in e invoicing portal
 
Dear Pranjal,
 
We are not passing “document_period_details” we are passing only “preceding_document_details” , still getting this error.
 
With .reference_details
          .invoice_remarks = ci800.t_invr
          Select Case ci800.t_dtyp
            Case "INV"
            Case Else
              .preceding_document_details = New List(Of miSubmitInvoice.cpreceding_document_details)
              Dim o_preceding_document_details As New SIS.CIISG.miSubmitInvoice.cpreceding_document_details
              With o_preceding_document_details
                .reference_of_original_invoice = ci800.t_prin
                .preceding_invoice_date = IIf(ci800.t_prid = "01/01/1970", "", ci800.t_prid)
                .other_reference = ci800.t_aore
              End With
              .preceding_document_details.Add(o_preceding_document_details)
          End Select
Regards
Veena
 
From: Pranjal Singh [mailto:pranjalsingh@mastersindia.co] 
Sent: 12 January 2021 18:22
To: Veena
Cc: mohinder pal singh; Parmanand Ranakoti; Baan Support
Subject: Re: FW: Error in uploading CDN in e invoicing portal
 
Hello Veena Ji,
 
I request you not to pass below-highlighted details
 
},
"reference_details": {
"invoice_remarks": "Invoice Remarks",
"document_period_details": {
"invoice_period_start_date": "2020-08-06",
"invoice_period_end_date": "2020-08-07"
},
 
On Tue, Jan 12, 2021 at 5:37 PM Veena <veena@isgec.co.in> wrote:
Dear Pranjal,
 
GSTN portal is giving following error on  posting of Debit Note. This debit note is not against any invoice.
Please resolve.
 
Regards
Veena
  
From: M P Singh [mailto:mpsingh@isgec.co.in] 
Sent: 12 January 2021 17:16
To: Baan Support Team-Isgec
Cc: veena.pawar@isgec.co.in; 'Rajiv Ajmani'
Subject: Error in uploading CDN in e invoicing portal
 
 We generated a CDN for claiming freight claim from customer but while uploading in e invoice portal below error is appearing
 
Regards
M.P.Singh
Acctt. Deptt.
Extn. 7241

**Comment by 0340LalitGupta** [comment]
Copied on live working fine. #

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
