### ISSUE TITLE
CR756-Supplier Registration Process to be covered in ERP

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#478]
Supplier   Registration Process to be covered in ERP(CR756)
--

**Comment by ravik200** [comment]
[Test Document for Vendor approval 10101 Request for Supplier Approval.docx](https://github.com/Isgec/ERPLN/files/5854610/Test.Document.for.Vendor.approval.10101.Request.for.Supplier.Approval.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Mr. Ajay Gupta on 18 May 2021 15:40

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by ravik200** [comment]
@veena-isgec mam, Solution GH478CR756_000 exported from server 37 to live and server 44.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close
