### ISSUE TITLE
166236-When TCS amount is chanced in Warehouse receipt, its corresponding data is not updated in tfacp935.

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#479]
When TCS amount is chanced in Warehouse receipt, its corresponding data is not updated in tfacp935.

**Comment by ravik200** [comment]
[Test Document for When TCS amount is chanced in Warehouse receipt.docx](https://github.com/Isgec/ERPLN/files/5865741/Test.Document.for.When.TCS.amount.is.chanced.in.Warehouse.receipt.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test the changes and uploaded test document.

**Comment by Pankaj9583** [comment]
[166236-Utility to develop remove and change TCS amount form table tfacp935 for avoid backend correct.docx](https://github.com/Isgec/ERPLN/files/5877892/166236-Utility.to.develop.remove.and.change.TCS.amount.form.table.tfacp935.for.avoid.backend.correct.docx)
Test done and its working fine (Test document attached for your reference)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, Moved to live and session added to Warehouse & Receipt menu.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
