### ISSUE TITLE
167803-Issue in freeze custom invoice against Generation of Commercial Invoice with Cr Note

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#480]
167803-Issue in freeze custom invoice against Generation of Commercial Invoice with Cr Note

**Comment by ravik200** [comment]
[Uploading Test Document for Issue in freeze custom invoice against Generation of Commercial Invoice with Cr Note.docx…]()
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
