### ISSUE TITLE
169071-Remove PO Series check  from Receipt correction sessions

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#481]
169071-User are not able to correct Purchase receipt tdpur4106s100 & Warehouse receipt whinh3121s000

PO series check is only desired for PO creation and amendments  not for receipts .

**Comment by ravik200** [comment]
[Test Document for Remove PO Series check  from Receipt correction sessions.docx](https://github.com/Isgec/ERPLN/files/5916410/Test.Document.for.Remove.PO.Series.check.from.Receipt.correction.sessions.docx)
Test Document

**Comment by Pankaj9583** [comment]
testing done and its working fine-
[Request for Backend Correction-Material Department.docx](https://github.com/Isgec/ERPLN/files/5918199/Request.for.Backend.Correction-Material.Department.docx)
Testing document attached

**Comment by veena-isgec** [comment]
tested ok

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
