### ISSUE TITLE
CR792-Modification in Commercial Invoice Print format based Custom Debit/Credit Notes

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#482]
CR792-Modification in Commercial Invoice Print format based Custom Debit/Credit Notes

**Comment by veena-isgec** [comment]
Received UAT mail from Chander Prakash on 03 February 2021 12:20

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
