### ISSUE TITLE
169176-Export incentives Status not free after reject sanction control by audit team. 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#483]
169176-Export incentives Status not free after reject sanction control by audit team.

**Comment by ravik200** [comment]
[Test Document for Export incentives Status not free after reject sanction control by audit team.docx](https://github.com/Isgec/ERPLN/files/5923566/Test.Document.for.Export.incentives.Status.not.free.after.reject.sanction.control.by.audit.team.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 Tested ok, please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
