### ISSUE TITLE
169255-E invoicing - Customer Debit/Credit Notes Manual Invoicing not opening-ciisg8505m000

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#485]
169255-E invoicing - Customer Debit/Credit Notes Manual Invoicing not opening-ciisg8505m000 due to zero record in table ciisg805. Deleted one zero value record from table. Issue to be fixed for future .

**Comment by ravik200** [comment]
@veena-isgec mam, In form set start command as find data in session ciisg8105m000, Now 0 record in not insert in table ciisg805,
Issue fixed in all server and no script changed.
