### ISSUE TITLE
169025-Issue in Purchase order printout if Purchase  order Line Qty and price 0.0000

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#486]
169025-Issue in Purchase order printout if Purchase  order Line Qty and price 0.0000

**Comment by ravik200** [comment]
[Test Document for ISSUE IN CALCULATING TAX VALUE IN PO PRINTOUT DUE TO RECEIVED QTY IS MORE THAN ORDER QTY.docx](https://github.com/Isgec/ERPLN/files/5948906/Test.Document.for.ISSUE.IN.CALCULATING.TAX.VALUE.IN.PO.PRINTOUT.DUE.TO.RECEIVED.QTY.IS.MORE.THAN.ORDER.QTY.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 please move to Live

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
