### ISSUE TITLE
166311-ISSUE IN CALCULATING TAX VALUE IN PO PRINTOUT DUE TO RECEIVED QTY IS MORE THAN ORDER QTY.

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#487]
From: Ajay Gupta [mailto:ajay.gupta@isgec.co.in] 
Sent: 01 February 2021 16:38
To: 'Baan Support Team-Isgec'
Cc: 'veena rani'
Subject: RE: P10148828 & P10148904 - ISSUE IN CALCULATING TAX VALUE 

Please proceed for correction

regards,
Ajay Gupta
85270 97888

From: Baan Support Team-Isgec [mailto:baansupport@isgec.co.in] 
Sent: 01 February 2021 16:27
To: ajay.gupta@isgec.co.in
Cc: 'veena rani'
Subject: RE: P10148828 & P10148904 - ISSUE IN CALCULATING TAX VALUE 
Importance: High

Dear Sir,

As discuss with veeen madam, we attached some PO 

Regards 
Baan Support Team
IT & System
 
A-8, Sector 63, Second Floor
Noida -201301 (UP)
0120-4085500, Extn No:- 7219
 Every 3000 sheets of paper cost us a tree. Let's consider our environmental responsibility before printing this e-mail - Save paper

From: Rahul Tejpal [mailto:rahul.tejpal@isgec.co.in] 
Sent: 01 February 2021 11:25
To: 'Baan Support Team-Isgec'
Cc: 'devansh gaur'; 'Ramesh Singh'; 'Ankit '
Subject: RE: P10148828 & P10148904 - ISSUE IN CALCULATING TAX VALUE 

Sir , 

Please arrange to resolve the issues related to subjected PO .

Best Regards ,

RAHUL TEJPAL 
Boiler-Materials
  
A-7, Sector-63, Noida – 201 301 U.P., India
Tel -  +91-120-408 7262
Mobile – 08448-055-966

**Comment by ravik200** [comment]
[Test Document for ISSUE IN CALCULATING TAX VALUE IN PO PRINTOUT DUE TO RECEIVED QTY IS MORE THAN ORDER QT1.docx](https://github.com/Isgec/ERPLN/files/5950109/Test.Document.for.ISSUE.IN.CALCULATING.TAX.VALUE.IN.PO.PRINTOUT.DUE.TO.RECEIVED.QTY.IS.MORE.THAN.ORDER.QT1.docx)
Test Document

**Comment by ravik200** [comment]
[Test Document for ISSUE IN CALCULATING TAX VALUE IN PO PRINTOUT DUE TO RECEIVED QTY IS MORE THAN ORDER QT1.docx](https://github.com/Isgec/ERPLN/files/5950173/Test.Document.for.ISSUE.IN.CALCULATING.TAX.VALUE.IN.PO.PRINTOUT.DUE.TO.RECEIVED.QTY.IS.MORE.THAN.ORDER.QT1.docx)
Updated Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Mr. Ajay Gupta on 10 February 2021 11:17

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
Moved to live working fine.
