### ISSUE TITLE
ERP sessions for Admin POs on test server

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#488]
"Maintain Admin Purchase Order"  http://192.168.9.251/isgecproject/PurchasesOrder.aspx?userid=AD0&username=ADMIN 
"Revise Admin Purchase Order"  http://192.168.9.251/isgecproject/revision_po.aspx?userid=AD0&username=ADMIN
"Admin PO Approval Master" http://192.168.9.251/isgecproject/Approval_type_master.aspx
"Admin PO Tax Codes" http://192.168.9.251/isgecproject/Tax_Code.aspx
"Admin PO Tax Types"http://192.168.9.251/isgecproject/taxtypemaster.aspx

**Comment by ravik200** [comment]
@veena-isgec mam, new session created in test server. PO admin(Menu) in distribution

**Comment by veena-isgec** [comment]
sessions created on test server
