### ISSUE TITLE
169703-Correction in Custom Invoice functionality to Post same Tax code and Isgec Registration in E-Invoicing and GSTR-1

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#489]
From: exportdocs-request@isgec.co.in [mailto:exportdocs-request@isgec.co.in] On Behalf Of Chander parkash
Sent: Wednesday, February 10, 2021 2:57 PM
To: 'Veena'
Cc: ''sudhir kumar nathani''; Bhupinder Kumar Malik; ''Parmanand Ranakoti''; 'Rajiv Ajmani '; exportdocs@isgec.co.in; 'Rahul Bansal'; Baan Support
Subject: [exportdocs] RE: e_Invocing for the month of Jan'21

Hi Ma’am

Good Day !!

GST-1 Report for the month of Jan’21 not showing  proper IGST Component &  GSTIN

Invoices have been raised in the 27AAACT5540K1Z7  but it showing in 09AAACT5540K2Z4

& Invoices have been raised with  ISGT 18%  & 28% but it is showing  nill Rate.

Soft Copies of Invoices are attached for  your ready reference.  

Thanks & Regards 

Chander  Parkash

![image](https://user-images.githubusercontent.com/43699482/107601895-eed2b500-6c4d-11eb-99e9-9f36e04272f5.png)

**Comment by ravik200** [comment]
[Test Document for.docx](https://github.com/Isgec/ERPLN/files/5979681/Test.Document.for.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test ASAP.

**Comment by Pankaj9583** [comment]
[169703-Correction in Custom Invoice functionality to Post same Tax code and Isgec Registration in E-Invoicing and GSTR-1_489.docx](https://github.com/Isgec/ERPLN/files/6114795/169703-Correction.in.Custom.Invoice.functionality.to.Post.same.Tax.code.and.Isgec.Registration.in.E-Invoicing.and.GSTR-1_489.docx)
Testing done and its working fine. Testing document attached

**Comment by veena-isgec** [comment]
@ravik200 tested ok, please move to live.

Regards
Veena

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
Moved to live , working fine.
