### ISSUE TITLE
CR817-Auditable PO Amendment checkbox to be provided in PO

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#490]
CR817-Auditable PO Amendment checkbox to be provided in PO

**Comment by veena-isgec** [comment]
UAT mail received from Ajay Gupta on 12 February 2021 16:01

**Comment by veena-isgec** [comment]
@ravik200 please move to Live.

**Comment by ravik200** [comment]
[Test Document for Auditable PO Amendment checkbox to be provided in PO.docx](https://github.com/Isgec/ERPLN/files/5979503/Test.Document.for.Auditable.PO.Amendment.checkbox.to.be.provided.in.PO.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, move to live

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
