### ISSUE TITLE
169794-Name of finalizer is not appearing while printing voucher from tfisg1402m000

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#491]
169794-Name of finalizer is not appearing while printing voucher from tfisg1402m000

**Comment by ravik200** [comment]
[Test Document for Name of finalizer is not appearing while printing voucher from tfisg1402m000.docx](https://github.com/Isgec/ERPLN/files/5979522/Test.Document.for.Name.of.finalizer.is.not.appearing.while.printing.voucher.from.tfisg1402m000.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 please  move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
