### ISSUE TITLE
157286-All Reasons and Remarks not appearing in report Print Audit Purchase Order Register

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#494]
In report Print Audit Purchase Order Register(tdisg0480m000), fields named “Rejection/Approval Reason” & “Rejection/Approval Remarks” showing only last 2 rows of the entries in PO Approval Session, it should display all reasons  & Remarks

**Comment by ravik200** [comment]
[Test Document for All Reasons and Remarks not appearing in report Print Audit Purchase Order Register.docx](https://github.com/Isgec/ERPLN/files/5994534/Test.Document.for.All.Reasons.and.Remarks.not.appearing.in.report.Print.Audit.Purchase.Order.Register.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Kamal on 16 March 2021 18:32. Please move to live

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
