### ISSUE TITLE
IR171202-In Project EC0034, PO P83006079 and P83006081 showing incorrect value in Linewise Po delivery status report

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#495]
In Project EC0034, PO P83006079 and P83006081 showing incorrect value in Linewise Po delivery status report

**Comment by ravik200** [comment]
[Test Document for Project EC0034.docx](https://github.com/Isgec/ERPLN/files/5994325/Test.Document.for.Project.EC0034.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 PO Linewise delivery status(tdisg4401m300) is ok, please move to live.
Please make same modification in tdisg4401m200 and tdisg4401m400 also.

**Comment by ravik200** [comment]
@veena-isgec mam,  PO Linewise delivery status(tdisg4401m300) is moved to live.

**Comment by ravik200** [comment]
[Test Document for  IR171202.docx](https://github.com/Isgec/ERPLN/files/6001243/Test.Document.for.IR171202.docx)
Test Document for modification in tdisg4401m200 and tdisg4401m400

**Comment by Pankaj9583** [comment]
Testing done in Print PO Wise Delivery status & Print PO Delivery status (Detailed)
 and its working fine (Testing document attached)
[Uploading IR171202-incorrect value in Linewise Po delivery status report.xlsx…]()

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, Both session tdisg4401m200 and tdisg4401m400 Moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
