### ISSUE TITLE
MSL76066-Balance in report "Print Finalized Transaction-Ledger Account - tfgls1406m000"

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#496]
Merino fixed the issue on on test server in above report rescript.
UAT mail received from Pawan. 

![image](https://user-images.githubusercontent.com/43699482/108192829-c01b7980-713a-11eb-8a0c-7752f3826abf.png)

**Comment by veena-isgec** [comment]
@ravik200 please upload scripts of these changes in github

**Comment by ravik200** [comment]
@veena-isgec mam, report script uploaded.

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
