### ISSUE TITLE
CR853-Report Required by Audit to display sanction changes due to Internal transfer or due to Client

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#497]
A New Report Required by Audit to display sanction changes due to Internal transfer or due to Client(This CR is replacement of CR0826)
--

**Comment by veena-isgec** [comment]
@ravik200 Please create a new session on live server in tpisg0407 series named "Sanction Addition/Reduction due to Internal transfer/Client" using following URL

http://192.9.200.158/Reports/Pages/Report.aspx?ItemPath=%2fP_SanctionTransferDuetoInternal_Client

**Comment by ravik200** [comment]
@veena-isgec mam, new session created (Session - tpisg0407m201) and added in menu URL Report

**Comment by veena-isgec** [comment]
source code updated in ssrs project

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
