### ISSUE TITLE
CR858-New Report for Element wise PO Placed vs sanction consumption

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#498]
CR858-New Report for Element wise PO Placed vs sanction consumption requested by Sachin Gupta

**Comment by ravik200** [comment]
[Test Document for Element wise PO Placed vs sanction consumption.docx](https://github.com/Isgec/ERPLN/files/6033814/Test.Document.for.Element.wise.PO.Placed.vs.sanction.consumption.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, New Solution GH498CR858_000 exported in server 37, Please move to live and 44 server

**Comment by veena-isgec** [comment]
@ravik200 add a new column in report output "Import PO Present(Y/N)", this column will be displayed after PO Placed column

**Comment by veena-isgec** [comment]
@ravik200 please updated latest script in github.

**Comment by ravik200** [comment]
@veena-isgec mam, latest script updated.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
