### ISSUE TITLE
CR834-FOC and FIM Transaction type of Billing assignments to reflect in two reports

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#499]
FOC and FIM Transaction type of Billing assignments to reflect in 
a) Maintain IR details session - tfisg0101m000
b) Payment Details (IR Wise) report tfisg0401m010

In case of FOC & FIM Billing transactions, STR is not assigned.
But this status is not visible to Material Accounts in their main reference reports.
Therefore, Material Accounts keep waiting for STR to reflect in above referred reports. Later after checking details of pending STR cases, Material Accounts comes to know of STR not required in such cases. This delays sending documents to finance. Hence FOC and FIM status of transaction type required to reflect in referred session and report.

**Comment by ravik200** [comment]
[Test Document for FOC and FIM Transaction type of Billing assignments to reflect in two reports.docx](https://github.com/Isgec/ERPLN/files/6007844/Test.Document.for.FOC.and.FIM.Transaction.type.of.Billing.assignments.to.reflect.in.two.reports.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Ajay Gupta on 25 February 2021 11:56

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
