### ISSUE TITLE
CR-859 disable field Advance on Service tax on session Billing Advice

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#500]
disable field "Advance on Service tax - tdisg831.sasa" on session "Billing Advice - tdisg8131m600".

**Comment by ravik200** [comment]
@veena-isgec mam, Field tdisg831.sasa disable in session "Billing Advice - tdisg8131m600" in all servers

**Comment by Pankaj9583** [comment]
[CR-859 disable field Advance on Service tax on session Billing Advice _500.docx](https://github.com/Isgec/ERPLN/files/6083966/CR-859.disable.field.Advance.on.Service.tax.on.session.Billing.Advice._500.docx)
Testing done & Its working fine (Document attached)
[Uploading CR-859 disable field Advance on Service tax on session Billing Advice _500.docx…]()

**Comment by veena-isgec** [comment]
@hariharan-isgec  solution moved to live, please close.

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
