### ISSUE TITLE
IR171679-Apply check in billing plan session that Instalment cannot be deleted if it is linked with Exports DR/CR Note.

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#502]
171679-Apply check in billing plan session that Instalment cannot be deleted if it is linked with Exports DR/CR Note.

**Comment by ravik200** [comment]
[Test Document for Apply check in billing plan session that Instalment cannot be deleted if it is linked with Exports DR.docx](https://github.com/Isgec/ERPLN/files/6059496/Test.Document.for.Apply.check.in.billing.plan.session.that.Instalment.cannot.be.deleted.if.it.is.linked.with.Exports.DR.docx)

Test Document

**Comment by Pankaj9583** [comment]
[IR 171679-Apply check in billing plan session that Instalment cannot be deleted if it is linked with Exports DR-CR Note._502.docx](https://github.com/Isgec/ERPLN/files/6088047/IR.171679-Apply.check.in.billing.plan.session.that.Instalment.cannot.be.deleted.if.it.is.linked.with.Exports.DR-CR.Note._502.docx)
Testing done and its working fine. (document attached)

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
