### ISSUE TITLE
CR850-Remove delete and cancel option from Purchase Order-Ajay Gupta

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#503]
Remove delete and cancel option from Purchase Order when Purchase order status <> Created
This request raised by Ajay Gupta to reduce back end corrections

**Comment by Pankaj9583** [comment]
Testing done and its working fine (Document Attached)
[CR850-Remove delete and cancel option from Purchase Order.docx](https://github.com/Isgec/ERPLN/files/6059637/CR850-Remove.delete.and.cancel.option.from.Purchase.Order.docx)

**Comment by veena-isgec** [comment]
UAT mail received from Ajay Gupta on 05 March 2021 16:11

**Comment by veena-isgec** [comment]
@ravik200 please move to live

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by ravik200** [comment]
@veena-isgec mam, cancel button disabled in Session tdpur4100m900(Purchase Order) in all the servers.

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
