### ISSUE TITLE
CR852-Receipt Correction option to be removed from Receipts

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#504]
Receipt Correction option to be removed from Receipts-Ajay Gupta
This option should remain available with baan support team

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hari solution moved to live , please close.

**Comment by veena-isgec** [comment]
@hariharan-isgec solution moved to live , please close.
