### ISSUE TITLE
CR851-Utility to set tax code/BP Registration Sequence to default after change of tax code in receipt

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#505]
Utility to set tax code/BP Registration Sequence to default after change of tax code in receipt

**Comment by ravik200** [comment]
[Test Document for Utility to set tax code.docx](https://github.com/Isgec/ERPLN/files/6090618/Test.Document.for.Utility.to.set.tax.code.docx)
test Document

**Comment by veena-isgec** [comment]
received UAT mail from Ajay Gupta on 12 March 2021 11:05

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, Solution GH505CR851_000 exported from server 37, Please move to live and server 44.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
