### ISSUE TITLE
IR171966-WHen transfer from CTOH amount not properly updated in L2 and L2 elements

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#506]
User did partial revise in sanction, moved amount from CTOH to element 50550000, L3 updated properly so there is no risk, however distributed amt of L1 and Total budget of L2 not properly updated.
This needs data correction. We are simulation this scenario to check whether this is repeated issue. 
[171966-Pls advise reg -65000 in sanction control JA0288.xlsx](https://github.com/Isgec/ERPLN/files/6048785/171966-Pls.advise.reg.-65000.in.sanction.control.JA0288.xlsx)

**Comment by Pankaj9583** [comment]
Its Wor
[Uploading IR171966-WHen transfer from CTOH amount not properly updated in L2 and L2 elements.xlsx…]()
king fine (testing document attached)

**Comment by veena-isgec** [comment]
Working fine. No Changes done in system. Issue could be transactional.
