### ISSUE TITLE
CR861-Statement for Import Purchase Orders

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#509]
Modify PO Linewise Delivery report for Import Purchase Orders

**Comment by ravik200** [comment]
[Test Document for Statement for Import Purchase Orders.docx](https://github.com/Isgec/ERPLN/files/6128314/Test.Document.for.Statement.for.Import.Purchase.Orders.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from SUraj Bhandari on 12 March 2021 18:25 on baansupport

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
