### ISSUE TITLE
CR819-Partial Element Status Tracker in Infor LN

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#510]
CR819-Partial Element Status Tracker in Infor LN

**Comment by ravik200** [comment]
[Test Document for Partial Element Status Tracker in Infor LN.docx](https://github.com/Isgec/ERPLN/files/6170973/Test.Document.for.Partial.Element.Status.Tracker.in.Infor.LN.docx)
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam, Solution GH510CR819_000 is exported from server 37, Please move to server 44.

**Comment by veena-isgec** [comment]
Under testing by Engineering

**Comment by veena-isgec** [comment]
UAT mail received from Mr. Pragasam on 22 April 2021 12:42

**Comment by veena-isgec** [comment]
@ravik200 please upload on live after office hours.

**Comment by ravik200** [comment]
@veena-isgec mam, Solution GH510CR819_000 is exported from server 37, Please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
