### ISSUE TITLE
172831-Apply check in Delivery challan should not be create if IR extension not maintain

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#511]
Apply check in Delivery challan should not be create if IR extension not maintain

**Comment by ravik200** [comment]
[Test Document for Apply check in Delivery challan should not be create if IR extension not maintain.docx](https://github.com/Isgec/ERPLN/files/6140719/Test.Document.for.Apply.check.in.Delivery.challan.should.not.be.create.if.IR.extension.not.maintain.docx)
Test Document

**Comment by Pankaj9583** [comment]
Testing done and its working fine (Testing document attached)
[172831-Apply check in Delivery challan should not be create if IR extension not maintain_517.docx](https://github.com/Isgec/ERPLN/files/6148859/172831-Apply.check.in.Delivery.challan.should.not.be.create.if.IR.extension.not.maintain_517.docx)

**Comment by veena-isgec** [comment]
@ravik200 tested ok, please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
