### ISSUE TITLE
171808-Utility for Doc no Expired but child item not expired in "Lot item creation session"

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#514]
Utility for Doc no Expired but child item not expired in "Lot item creation session"

**Comment by ravik200** [comment]
[Test Document for Utility for Doc no Expired but child item not expired in.docx](https://github.com/Isgec/ERPLN/files/6154929/Test.Document.for.Utility.for.Doc.no.Expired.but.child.item.not.expired.in.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test this github

**Comment by ravik200** [comment]
@veena-isgec mam, done through Github no. #518

**Comment by veena-isgec** [comment]
done through Github no. #518
