### ISSUE TITLE
Modification in Billing Advice(Projects ) session to consider Exports DR/CR Notes amount in LC Balance

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#516]
Modification in Billing Advice(Projects ) session to consider Exports DR/CR Notes amount in LC Balance

**Comment by veena-isgec** [comment]
@ravik200 tested ok, please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
