### ISSUE TITLE
Modification in Billing Plan session to consider Export DR/CR note while calculation balance to be assigned value

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#517]
Modification in Billing Plan session to consider Export DR/CR note while changing Billing schedule amount. Error screenshot attached

![image](https://user-images.githubusercontent.com/43699482/110906286-c237b900-8331-11eb-826a-23b0172ca9ad.png)

**Comment by ravik200** [comment]
[Test Document for Modification in Billing Plan session to consider Export DR.docx](https://github.com/Isgec/ERPLN/files/6129427/Test.Document.for.Modification.in.Billing.Plan.session.to.consider.Export.DR.docx)
Test Document

**Comment by Pankaj9583** [comment]
testing done and its working done (Document attached)
[517_Modification in Billing Plan session to consider Export DR-CR note while calculation balance to be assigned value.docx](https://github.com/Isgec/ERPLN/files/6148762/517_Modification.in.Billing.Plan.session.to.consider.Export.DR-CR.note.while.calculation.balance.to.be.assigned.value.docx)

**Comment by veena-isgec** [comment]
@ravik200 tested ok, please move to live

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
