### ISSUE TITLE
Utility to correct Item status where Document expired, Item not expired

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#518]
Utility to correct Item status where Document expired, Item not expired

Logic to be used - 
select 
dmisg005.cprj as Project,
dmisg005.cspa as Element,
dmisg005.docn as Document,
dmisg005.revn as Revision,
dmisg005.item as Item
  from dmisg005 , tdmisg001
where dmisg001200.docn = dmisg005.docn 
and dmisg001200.revn = dmisg005.revn
and dmisg005200.stat <> dmisg001.stat 
and dmisg005200.stat = 3
and dmisg001200.stat = 4

History to be maintained for each changed record of dmisg005 with old status, new status, user and datetime

**Comment by ravik200** [comment]
[Uploading Test Document for Utility for Doc no Expired but child item not expired in.docx…]()
Test Document

**Comment by ravik200** [comment]
@veena-isgec mam Solution GH518CR000_000 exported from server 37, Please move to server 44.

**Comment by Pankaj9583** [comment]
[Utility to correct Item status where Document expired, Item not expired _518.docx](https://github.com/Isgec/ERPLN/files/6196171/Utility.to.correct.Item.status.where.Document.expired.Item.not.expired._518.docx)
Testing done and it's working fine  (Document attached)

**Comment by ravik200** [comment]
@veena-isgec mam moved to live and sessions are in Item release Menu

**Comment by veena-isgec** [comment]
@hariharan-isgec Moved to live. Working fine. Please close
