### ISSUE TITLE
Modification in Billing Advice Projects session lines to consider exports DR CR amt while calculating balance billing amount

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#521]
Modification in Billing Advice Projects session lines to consider exports DR CR amt while calculating balance billing amount

![image](https://user-images.githubusercontent.com/43699482/111113060-2acba380-8587-11eb-9609-881b3d39a5bb.png)

**Comment by ravik200** [comment]
[Test Document for Modification in Billing Advice Projects session lines to consider exports DR CR amt while calculating balance billing amount.docx](https://github.com/Isgec/ERPLN/files/6140276/Test.Document.for.Modification.in.Billing.Advice.Projects.session.lines.to.consider.exports.DR.CR.amt.while.calculating.balance.billing.amount.docx)
Test Document, Testing done in live server

**Comment by ravik200** [comment]
@veena-isgec mam moved to live

**Comment by veena-isgec** [comment]
Moved to live. working fine.
