### ISSUE TITLE
173117-Due to limitation of character limit in BaaN, please allow to print full name of company  in "Annexure to export Invoice No"

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#524]
173117-Due to limitation of character limit in BaaN, please allow to print full name of company  in "Annexure to export Invoice No"
![image](https://user-images.githubusercontent.com/43699482/111264115-f6bab600-864c-11eb-94c4-ec717f58bbd2.png)

**Comment by veena-isgec** [comment]
@Pankaj9583 Please test.

**Comment by ravik200** [comment]
[Test Document for Due to limitation of character limit in BaaN.docx](https://github.com/Isgec/ERPLN/files/6154229/Test.Document.for.Due.to.limitation.of.character.limit.in.BaaN.docx)
Test Document

**Comment by Pankaj9583** [comment]
Testing done and its working fine (Testing document attached)
[Uploading 173117-Due to limitation of character limit in BaaN please allow to print full name of company in Annexure to export Invoice No_524.docx…]()

**Comment by veena-isgec** [comment]
@ravik200 tested ok, please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
