### ISSUE TITLE
Modification in E-invoicing of DR/CR Note/Manual Invoicing session

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#525]
Document No. zoom should show document of selected company, presently it is showing company only.
![image](https://user-images.githubusercontent.com/43699482/111741536-a5106680-88ac-11eb-8495-8672256cdab1.png)

**Comment by Pankaj9583** [comment]
[Modification in E-invoicing of DR-CR Note-Manual Invoicing session_525.docx](https://github.com/Isgec/ERPLN/files/6196252/Modification.in.E-invoicing.of.DR-CR.Note-Manual.Invoicing.session_525.docx)
Testing done and it's working fine (Testing document attached)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
