### ISSUE TITLE
CR866-Modification in report "Print L3 level element Element vs Engineering Weight"

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#526]

**Comment by ravik200** [comment]
[Test Document for Modification in report Print L3 level element Element vs Engineering Weight.docx](https://github.com/Isgec/ERPLN/files/6194476/Test.Document.for.Modification.in.report.Print.L3.level.element.Element.vs.Engineering.Weight.docx)
Test Document

**Comment by veena-isgec** [comment]
Under testing by Engineering

**Comment by veena-isgec** [comment]
UAT mail received from Rajesh on 06 April 2021 10:52

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
