### ISSUE TITLE
CR868-Modification in Transmittal Creation and Approval Sessions

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#527]
CR868-Modification in Transmittal Creation and Approval Sessions

**Comment by ravik200** [comment]
[Test Document for Modification in Transmittal Creation and Approval Sessions.docx](https://github.com/Isgec/ERPLN/files/6209730/Test.Document.for.Modification.in.Transmittal.Creation.and.Approval.Sessions.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT Mail received from Rajesh on 06 April 2021 16:06

**Comment by veena-isgec** [comment]
From: Ravi Kumar [mailto:ravi.kumar2@isgec.co.in] 
Sent: 07 April 2021 11:00
To: 'Veena'
Subject: RE: CR868-Modification in Transmittal Creation and Approval Sessions #527.xlsx

Dear mam,

Send Status added in session dmisg1131m100 in test servers.

 

Regards,
Ravi Kumar

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live, please close.
