### ISSUE TITLE
CR878-Modification in Logistics PO Generation from Superprocure utility

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#528]
Modification in Logistics PO Generation from Superprocure utility

**Comment by ravik200** [comment]
[Uploading Test Document for Modification in Logistics PO Generation from Superprocure utility.docx…]()
Test Document

**Comment by veena-isgec** [comment]
@ravik200 I have tested it, working fine, please move to live for further testing.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live , please close.
