### ISSUE TITLE
174937-Text is not fully getting printed on HTML Sale invoice 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#530]
Text entered in “Maintain project wise extension” (tpisgo145m000) session, is not fully getting printed on Sale invoice print session(ciisg2405m105)

**Comment by ravik200** [comment]
[Test Document for Text is not fully getting printed on HTML Sale invoice.docx](https://github.com/Isgec/ERPLN/files/6203462/Test.Document.for.Text.is.not.fully.getting.printed.on.HTML.Sale.invoice.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 pls move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
