### ISSUE TITLE
174852-restrict zero serial no. in Sales DR CR Note/Manual Invoicing session

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#531]
174852-restrict zero serial no. in Sales DR CR Note/Manual Invoicing session
Data in E-Invoicing Item table should be deleted and reinserted every time user selects "Upload E-Invoicing Data" option
![image](https://user-images.githubusercontent.com/43699482/112433440-46456400-8d68-11eb-9477-1bb08e087125.png)

**Comment by ravik200** [comment]
[Test Document for Restrict zero serial no.docx](https://github.com/Isgec/ERPLN/files/6204286/Test.Document.for.Restrict.zero.serial.no.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test this github

**Comment by Pankaj9583** [comment]
Testing done and its working fine (Testing document attached)
[74852-restrict zero serial no. in Sales DR CR Note-Manual Invoicing session _531.docx](https://github.com/Isgec/ERPLN/files/6269128/74852-restrict.zero.serial.no.in.Sales.DR.CR.Note-Manual.Invoicing.session._531.docx)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live, please close.
