### ISSUE TITLE
175066-Open selected project in session Transfer to supply element from freight/P&F/TPC log from Sanction control 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#532]
175066-Open same project code while open session Transfer to supply element from freight/P&F/TPC log in Sanction control

**Comment by ravik200** [comment]
[Test Document for Open selected project in session Transfer to supply element from freight.docx](https://github.com/Isgec/ERPLN/files/6226444/Test.Document.for.Open.selected.project.in.session.Transfer.to.supply.element.from.freight.docx)
Test Document

**Comment by Pankaj9583** [comment]
Testing done and its working fine. (Testing Document attached)
[175126-Kindly delete the below elements 99022520-99022555-99022570 in sanction control JE1926.docx](https://github.com/Isgec/ERPLN/files/6226446/175126-Kindly.delete.the.below.elements.99022520-99022555-99022570.in.sanction.control.JE1926.docx)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, Moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
