### ISSUE TITLE
175083 -Issue Standard Item code show double in display item master

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#533]
In assign LOT Item session on Item Release, if Item already released then it should not release again

**Comment by ravik200** [comment]
[Test Document for Issue Standard Item code show double in display item master.docx](https://github.com/Isgec/ERPLN/files/6242863/Test.Document.for.Issue.Standard.Item.code.show.double.in.display.item.master.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 , please test.

**Comment by veena-isgec** [comment]
@Pankaj9583 , please test.

**Comment by Pankaj9583** [comment]
Testing done and its working fine (Testing document
[Uploading 175083 -Issue Standard Item code show double in display item master_533.docx…]()
 attached)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live , please close.
