### ISSUE TITLE
175195-Correction in display value of custom invoice in Shipping Bill linking session tdisg8145m000

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#534]
175195-Please note that we have increased invoice value from $ 63000 to $ 65,334.09 by raised debit note for USD 2334.09. (copy of debit note and invoice attached) ISG202627 .
To resolve above issue Please do following-
1. Correction in display value of custom invoice in Shipping Bill linking session, amount should be net amount of custom invoice after consideration of linked DR CR notes
2. "Custom Invoice no. Already linked with Shipping Bill No., only one invoice can be linked", this error should not consider current invoice while changing value of shipping bill.

**Comment by ravik200** [comment]
@veena-isgec mam, done in all servers.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
