### ISSUE TITLE
In Generate commercial Invoice session E-Invoicing  check to be applied

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#535]
IF EBA type is "SUPPLY" and Country of Origin is "India" then E_Invoice of selected custom Invoice and DR CR Note is to be made mandatory else error message "E_Invoice of Custom Invoice xxxxxxxxx not done" or "E-Invoice of DR CR Note xxxxxxxxx not done" and not generate commercial Invoice

![image](https://user-images.githubusercontent.com/43699482/113131273-a2155e80-923a-11eb-9ec4-3b1750d6afa9.png)

**Comment by ravik200** [comment]
@veena-isgec mam, Done in all server(Check applied)

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live , please close.
