### ISSUE TITLE
CR883-Minimum 6 digit HSN code to be made mandatory in Domestic Billing Advice

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#536]
Minimum 6 digit HSN code to be made mandatory in Domestic Billing Advice
--

**Comment by ravik200** [comment]
[Test Document for Minimum 6 digit HSN code to be made mandatory in Domestic Billing Advice.docx](https://github.com/Isgec/ERPLN/files/6241195/Test.Document.for.Minimum.6.digit.HSN.code.to.be.made.mandatory.in.Domestic.Billing.Advice.docx)
Test Document

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live , please close.
