### ISSUE TITLE
175410-GST Taxes not coming in PO print when manual amount is entered in ASV Price for GST in PO line

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#537]
175410-GST Taxes not coming in PO print when manual amount is entered in ASV Price for GST in PO line

**Comment by ravik200** [comment]
[Test Document for GST Taxes not coming in PO print when manual amount is entered in ASV Price for GST in PO line.docx](https://github.com/Isgec/ERPLN/files/6247726/Test.Document.for.GST.Taxes.not.coming.in.PO.print.when.manual.amount.is.entered.in.ASV.Price.for.GST.in.PO.line.docx)
Test Document

**Comment by Pankaj9583** [comment]
Testing done and it's working fine (Testing Document Attached)
[175410-GST Taxes not coming in PO print when manual amount is entered in ASV Price for GST in PO line_537.docx](https://github.com/Isgec/ERPLN/files/6247826/175410-GST.Taxes.not.coming.in.PO.print.when.manual.amount.is.entered.in.ASV.Price.for.GST.in.PO.line_537.docx)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, working fine, please close.
