### ISSUE TITLE
CR880-Remove cancellation option from Indent Value Increase Request

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#538]
CR880-Remove cancellation option from Indent Value Increase Request

**Comment by ravik200** [comment]
@veena-isgec mam, Cancel button remove from Session tdisg4160m000(function cancel_request with field group dsca) in all the server.

**Comment by veena-isgec** [comment]
@hariharan-isgec changes moved to live. No change in script. Please close.
