### ISSUE TITLE
CR881-Provision for writing Header Text Fields in PO

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#539]
CR881-Provision for writing Header Text Fields in PO

![image](https://user-images.githubusercontent.com/43699482/113296592-4c62b400-9317-11eb-91f1-db12f6a62ef3.png)

**Comment by ravik200** [comment]
[Test Document for Provision for writing Header Text Fields in PO.docx](https://github.com/Isgec/ERPLN/files/6335892/Test.Document.for.Provision.for.writing.Header.Text.Fields.in.PO.docx)
Test Document

**Comment by veena-isgec** [comment]
Under Testing by Mr. Ajay Gupta.

**Comment by veena-isgec** [comment]
UAT mail received from Ajay Gupta on 20 April 2021 10:58

**Comment by veena-isgec** [comment]
@ravik200 please plan to move to live today after office hours.

**Comment by ravik200** [comment]
@veena-isgec mam, move to live

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live , please close.
