### ISSUE TITLE
CR871- Indent Increase request should follow same authorization matrix as Indent

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#540]
CR871- Indent Increase request should follow same authorization matrix as Indent

**Comment by ravik200** [comment]
[Test Document for Indent Increase request should follow same authorization matrix as Indent.docx](https://github.com/Isgec/ERPLN/files/6277750/Test.Document.for.Indent.Increase.request.should.follow.same.authorization.matrix.as.Indent.docx)

Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test

**Comment by Pankaj9583** [comment]
testing Done and its working fine (Testing document attached)
[CR871- Indent Increase request should follow same authorization matrix as Indent.docx](https://github.com/Isgec/ERPLN/files/6310192/CR871-.Indent.Increase.request.should.follow.same.authorization.matrix.as.Indent.docx)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live please close
