### ISSUE TITLE
CR873-Common Manhours booking reports to be developed for Isgec and Redecam

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#542]
CR873-Common Manhours booking reports to be developed for Isgec and Redecam
--

**Comment by ravik200** [comment]
[Test Document for Common Manhours booking reports to be developed for Isgec and Redecam.docx](https://github.com/Isgec/ERPLN/files/6315463/Test.Document.for.Common.Manhours.booking.reports.to.be.developed.for.Isgec.and.Redecam.docx)
Test Document

**Comment by veena-isgec** [comment]
Under Testing by Rajesh.

**Comment by veena-isgec** [comment]
UAT mail received from Rajesh on 05 May 2021 15:14

**Comment by veena-isgec** [comment]
@ravik200 Please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to love, please close

**Comment by ravik200** [comment]
Print main Hour session logic changed for comp 810 due to cannot add comp 810 with 200, 651 & 700
