### ISSUE TITLE
No change in Isgec GSTIN in EBA after E-Invoicing of custom Invoice(tdisg831)

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#543]
No change in Isgec GSTIN in EBA after E-Invoicing of custom Invoice

**Comment by veena-isgec** [comment]
If GSTIN in tdisg831 and GST compliance session are different then show error message at the time of E-invoicing of Custom Invoice and  print of custom invoice (html) and stop the process.

**Comment by veena-isgec** [comment]
@ravik200 Please update status of this github.

**Comment by ravik200** [comment]
@veena-isgec mam, no changes done

**Comment by veena-isgec** [comment]
@ravik200 why?

**Comment by ravik200** [comment]
[Test Document for No change in Isgec GSTIN in EBA after E.docx](https://github.com/Isgec/ERPLN/files/6308256/Test.Document.for.No.change.in.Isgec.GSTIN.in.EBA.after.E.docx)
Test Document

**Comment by Pankaj9583** [comment]
Testing done and its working fine (Testing document attached)
[No change in Isgec GSTIN in EBA after E-Invoicing of custom Invoice_543.docx](https://github.com/Isgec/ERPLN/files/6309586/No.change.in.Isgec.GSTIN.in.EBA.after.E-Invoicing.of.custom.Invoice_543.docx)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live
