### ISSUE TITLE
176242-Billing advice cannot be deleted if receipt already link in billing advice 

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#544]
176242-Billing advice cannot be deleted if receipt already link in billing advice

**Comment by ravik200** [comment]
[Test Document for Billing advice cannot be deleted if receipt already link in billing advice.docx](https://github.com/Isgec/ERPLN/files/6317190/Test.Document.for.Billing.advice.cannot.be.deleted.if.receipt.already.link.in.billing.advice.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test

**Comment by Pankaj9583** [comment]
Testing done and its working fine (Testing document attached)
[176242-Billing advice cannot be deleted if receipt already link in billing advice_544.docx](https://github.com/Isgec/ERPLN/files/6317239/176242-Billing.advice.cannot.be.deleted.if.receipt.already.link.in.billing.advice_544.docx)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec , moved to live , please close.
