### ISSUE TITLE
176573-Payment detail (IR wise) and Payment detail MSME (IR wise) showing deleted PTRs

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#546]
176573-Payment detail (IR wise) and Payment detail MSME (IR wise) showing deleted PTRs
source of PTR to be changed from tfisg001 to tfacp100

**Comment by ravik200** [comment]
[Test Document for Payment detail.docx](https://github.com/Isgec/ERPLN/files/6382470/Test.Document.for.Payment.detail.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 , Please test this github.

**Comment by Pankaj9583** [comment]
Testing done and its working fine now. (Testing document attached)
[176573-Payment detail -IR wise and Payment detail MSME-IR wise showing deleted PTRs.docx](https://github.com/Isgec/ERPLN/files/6419192/176573-Payment.detail.-IR.wise.and.Payment.detail.MSME-IR.wise.showing.deleted.PTRs.docx)

**Comment by veena-isgec** [comment]
@ravik200 pls move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
