### ISSUE TITLE
CR882-Modification in Indent Types

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#547]
Replacement of dropdowns in “Purchase Requisition Details” session for the different types of Indents we make with the following mentioned 5 dropdowns.
1. Bought-Out
2. Fabrication
3. Services
4. Freight & Logistics
5. Spares
Further this detail should be reflected in the session “Pending Indents Report (tdisg2401m001)” in an additional column so that the segregation of data could be simplified.
For more details refer email communication to Baan Support by MD ASHRAF RAZI Dated 30.03.2021 @13:07PM

**Comment by ravik200** [comment]
[Test Document for Modification in Indent Types.docx](https://github.com/Isgec/ERPLN/files/6389183/Test.Document.for.Modification.in.Indent.Types.docx)
Test Document

**Comment by veena-isgec** [comment]
UAT mail received from Ashraf on 30 April 2021 20:09 , he tested on server 37.

**Comment by veena-isgec** [comment]
@ravik200 please upload on love, user tested on server 37.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live.

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live please close.
