### ISSUE TITLE
177091-Change series from "41" to "42" in session "Input Tax Credit Utility"

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#549]
177091-Change series from "41" to "42" in session "Input Tax Credit Utility"

**Comment by veena-isgec** [comment]
@ravik200 Please do it on all test as well as live servers.

**Comment by ravik200** [comment]
@veena-isgec mam, done in all test and live servers

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live please close.
