### ISSUE TITLE
CR827-MSME Code required in Print Purchase Bill Approval Memo

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#551]
CR827-MSME Code required in Print Purchase Bill Approval Memo

**Comment by ravik200** [comment]
[Test Document for MSME Code required in Print Purchase Bill Approval Memo.docx](https://github.com/Isgec/ERPLN/files/6441773/Test.Document.for.MSME.Code.required.in.Print.Purchase.Bill.Approval.Memo.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.

**Comment by Pankaj9583** [comment]
Testing Done & its working fine (Testing document attached)
[CR827-MSME Code required in Print Purchase Bill Approval Memo_551.docx](https://github.com/Isgec/ERPLN/files/6463712/CR827-MSME.Code.required.in.Print.Purchase.Bill.Approval.Memo_551.docx)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
