### ISSUE TITLE
CR828-MSME Code required in Print Voucher (Purchase)

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#552]
CR828-MSME Code required in Print Voucher (Purchase)

**Comment by ravik200** [comment]
[Uploading Test Document for MSME Code required in Print Voucher.docx…]()
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.

**Comment by Pankaj9583** [comment]
Testing done & its working done (Testing document attached)
[CR828-MSME Code required in Print Voucher _Purchase_(552.docx](https://github.com/Isgec/ERPLN/files/6463604/CR828-MSME.Code.required.in.Print.Voucher._Purchase_.552.docx)

**Comment by veena-isgec** [comment]
Got UAT from Mr. Saha on 05-05-2021 13:15 by demonstrating test document.
@ravik200 please move to live

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
