### ISSUE TITLE
177201-Approver Name not appearing correct in History of “Indent Value Increase”

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#553]
177201-Corretion required History of “Indent Value Increase” session tdisg4562m00 for display in "Approval in rejection remarks field"

**Comment by ravik200** [comment]
[Uploading Test Document for Approver Name not appearing correct in History of.docx…]()
Test Document

**Comment by Pankaj9583** [comment]
Testing Done and its working fine (Testing Document attached)
[177201-Approver Name not appearing correct in History of “Indent Value Increase_553.docx](https://github.com/Isgec/ERPLN/files/6463721/177201-Approver.Name.not.appearing.correct.in.History.of.Indent.Value.Increase_553.docx)

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close
