### ISSUE TITLE
CR707-Report of Documents received in accounts required

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#555]
Please create session to open following ssrs report from ERP in series tfisg1483 series
Session Name : "Tracking Report of Supplier Documents Received in Accounts"

http://192.9.200.158/Reports/Pages/Report.aspx?ItemPath=%2fP_TrackingOfDocumentsReceivedinAccounts

**Comment by ravik200** [comment]
@veena-isgec new session tfisg1483m001 created in live server.

**Comment by veena-isgec** [comment]
SSRS report provided on live as per discussion with ACP Incharge Saha JI

**Comment by veena-isgec** [comment]
@ravik200 please upload source code in github

**Comment by ravik200** [comment]
@veena-isgec mam, Source code uploaded.

**Comment by veena-isgec** [comment]
@hariharan-isgec created in live, please close.
