### ISSUE TITLE
CR888-To modify the range of filter named “Delivery Date” to current date+3 years

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#557]
CR888-To modify the range of filter named “Delivery Date” to current date+3 years

**Comment by veena-isgec** [comment]
[CR888-To modify the range of filter named Delivery Date to current date+3 years #557.xlsx](https://github.com/Isgec/ERPLN/files/6508473/CR888-To.modify.the.range.of.filter.named.Delivery.Date.to.current.date%2B3.years.557.xlsx)

**Comment by ravik200** [comment]
[Test Document for To modify the range of filter named Delivery Date to current date.docx](https://github.com/Isgec/ERPLN/files/6522621/Test.Document.for.To.modify.the.range.of.filter.named.Delivery.Date.to.current.date.docx)
Test Document

**Comment by veena-isgec** [comment]
@Pankaj9583 please test

**Comment by Pankaj9583** [comment]
testing done and its working fine (Testing document attached)
[CR888-To modify the range of filter named “Delivery Date” to current date+3 year_s557.docx](https://github.com/Isgec/ERPLN/files/6525902/CR888-To.modify.the.range.of.filter.named.Delivery.Date.to.current.date%2B3.year_s557.docx)

**Comment by veena-isgec** [comment]
@ravik200 working fine, please move to live

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live, please close.
