### ISSUE TITLE
CR885-Add PO Item reference  in Sanction Short email

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#558]
CR885-Add PO Item reference  in Sanction Short email

**Comment by veena-isgec** [comment]
@ravik200 SRS uploaded
[CR885-Add PO Item reference in Sanction Short email #558.xlsx](https://github.com/Isgec/ERPLN/files/6508594/CR885-Add.PO.Item.reference.in.Sanction.Short.email.558.xlsx)

**Comment by veena-isgec** [comment]
@Pankaj9583 please test

**Comment by veena-isgec** [comment]
@Pankaj9583 please test

**Comment by veena-isgec** [comment]
@Pankaj9583 please test.

**Comment by ravik200** [comment]
[Test Document for Add PO Item reference in Sanction Short email.docx](https://github.com/Isgec/ERPLN/files/6552981/Test.Document.for.Add.PO.Item.reference.in.Sanction.Short.email.docx)
Test Document

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by Pankaj9583** [comment]
Testing done and its working fine (Testing document attached)
[CR885-Add PO Item reference  in Sanction Short email (#558).docx](https://github.com/Isgec/ERPLN/files/6553806/CR885-Add.PO.Item.reference.in.Sanction.Short.email.558.docx)

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live Please close
