### ISSUE TITLE
CR891-Cashflow activation in company 651

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#565]
CR891-Cashflow activation in company 651

**Comment by veena-isgec** [comment]
[CR891-Cashflow activation in company 651 #565.xlsx](https://github.com/Isgec/ERPLN/files/6551536/CR891-Cashflow.activation.in.company.651.565.xlsx)

**Comment by veena-isgec** [comment]
UAT mail received from Pawan on 31 May 2021 17:18

**Comment by veena-isgec** [comment]
@ravik200 please move to live.

**Comment by ravik200** [comment]
@veena-isgec mam, moved to live

**Comment by veena-isgec** [comment]
@hariharan-isgec moved to live. Please close
