### ISSUE TITLE
186873-New button to be disabled from session tctax4100m000 when opened from IR extension

### ISSUE THREAD

**Issue by veena-isgec** [Isgec/ERPLN#630]
186873-New Field to be disabled from session tctax4100m000 when zoomed from IR extension tfisg4105m000 

![image](https://user-images.githubusercontent.com/43699482/130236829-9f611fea-b74d-4e59-8aa6-d3583d164fc6.png)

**Comment by veena-isgec** [comment]
Done
![image](https://user-images.githubusercontent.com/43699482/139658857-621efe64-4a99-4d78-88f3-fc3fa09aff8a.png)

**Comment by veena-isgec** [comment]
@utam-singh Can you please update script in this github.

**Comment by utam-singh** [comment]
@veena-isgec mam, No Change in Script.
