### ISSUE TITLE
Document Tracking - IR level W/F and Reason entry

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/ERPLN#9]
In Document Tracking currently W/F is done at every line and only one reason (code) can be assigned. 
Change Required:-
W/F to be done at IR level (new session to open from current session 
To create provision to add 5 reasons. 5th Reason could be OTHER, then a Description to be given by user  

@veena-isgec to develop internally
Agreements:
Accounts will reduce the number of Reasons-Series 100 to 500 are of Billing 500 to 600 of Vendor 600+ GST related.

Caveat:
When Material Accounts forwards Original Bill for Supplier Payment they are not using DTS

**Comment by veena-isgec** [comment]
tested and uploaded on live.
